function LEN_HOUR(a){if(""==a.value)a.value="00";else{a=a.id;var b="",b=document.getElementById(a).value.length;"1"==b&&(document.getElementById(a).value="0"+document.getElementById(a).value)}}function LEN_HOUR_NULL(a){if(""==a.value)a.value="";else{a=a.id;var b="",b=document.getElementById(a).value.length;"1"==b&&(document.getElementById(a).value="0"+document.getElementById(a).value)}}function CheckFloat(a){var b=0,b=""==a?0:parseFloat(a);return Math.round(100*b)/100}
function ValidateNumeric(){var a=window.event.keyCode;if(48>a||57<a)window.event.returnValue=!1}function ValidateDecimal(){var a=window.event.keyCode;if(46!=a&&(48>a||57<a))window.event.returnValue=!1}function collapse(a,b){null==b?"none"==document.getElementById(a).style.display?document.getElementById(a).style.display="":document.getElementById(a).style.display="none":!1==b?document.getElementById(a).style.display="none":document.getElementById(a).style.display="";return!1}
function showReportOnly(){isDisplay=document.getElementById("_ctl0_chkShowGrid").checked;collapse("tdPages",isDisplay);collapse("trGrid",isDisplay);!0==isDisplay&&!0==document.getElementById("_ctl0_chkSort").checked?collapse("tdSort",isDisplay):collapse("tdSort",!isDisplay)}
function ShowDialog(a,b,d){if(null==b||100>b)b=Math.round(2*(screen.width/3))+100;b>screen.width&&(b=screen.width-100);if(null==d||100>d)d=Math.round(2*(screen.height/3));d>screen.height&&(d=screen.height-100);t=l=0;-1!=a.indexOf("MdlSYS/Form/MailPopup.ascx")&&-1!=a.indexOf("AutoSend=1")&&(t=l=1E3,d=b=0);objShowDialog=window.open(a,"Recipient","status=1,toolbar=0,scrollbars=1,resizable=1,alwaysRaised=Yes, top="+t+", left="+l+", width="+b+", height="+d+",1 ,align=center");objShowDialog.focus()}
function gshowModalDialog(a,b,d){if(null==b||100>b)b=Math.round(2*(screen.width/3));b>screen.width&&(b=screen.width-100);if(null==d||100>d)d=Math.round(2*(screen.height/3));d>screen.height&&(d=screen.height-100);t=l=0;objShowDialog=window.showModalDialog(a,"Recipient","status=0;scroll=1;resizable=yes;alwaysRaised=Yes; dialogHeight="+d+"px; dialogWidth="+b+"px;align=center")}function KeyDownHandler(a){13==event.keyCode&&(event.returnValue=!1,event.cancel=!0,document.getElementById().click(a))}
function GridCheck(a,b,d,c){var e,f;e=document.getElementById(a).rows.length;f=!0;if(1<e)for(;b<document.getElementById(a).rows.length+d;b++)if(!0==document.getElementById(a+"__ctl"+b+"_"+c).checked){f=!1;break}return f?!1:!0}
function checkNumeric_(a,b,d){if(null!=a&&""!=a.value){var c;c=/,/g;var e=a.value.replace(c,"");c=/\s+/;e=e.replace(c,"");if(""==e)a.value="";else{if(isNaN(e))return GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus(),!1;if(0>e)return GetAlertError(iTotal,DSAlert,"00012"),a.value="",a.focus(),!1;if(e<b)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0059").replace("@",b)),a.value="",a.focus(),!1;if(e>d)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0054").replace("@",d)),a.value=
"",a.focus(),!1;FormatNumericWithSeparate(a)}}}function ClearRadComboSelection(a){try{a.set_text(""),a.set_value(""),a.clearSelection()}catch(b){}}
function checkNumeric__(a,b,d){if(null!=a&&""!=a.value){var c;c=/,/g;var e=a.value.replace(c,"");c=/\s+/;e=e.replace(c,"");if(""==e)a.value="";else{if(isNaN(e))return GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus(),!1;if(e<b)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0059").replace("@",b)),a.value="",a.focus(),!1;if(e>d)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0054").replace("@",d)),a.value="",a.focus(),!1;FormatNumericWithSeparate(a)}}}
function checkNumeric_returnNull(a,b){if(""!=a.value){var d=a.value.replace(/,/g,"");if(isNaN(d))return GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus(),!1;if(0>d)return GetAlertError(iTotal,DSAlert,"0012"),a.value="",a.focus(),!1;if(d>b)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0054").replace("@",b)),a.value="",a.focus(),!1;FormatNumericWithSeparate(a)}}
function FillRadGrid(a,b,d,c,e,f){a=$find("_ctl0_"+a).get_masterTableView();var g=a.get_dataItems().length;if(0<g)for(i=0;i<g;i++){var h=a.get_dataItems()[i],j=h.findElement(b);h.findElement(d);try{j.checked&&("radcombo"==c.toLowerCase()?($find(h.findElement(d).id).set_text(f),$find(h.findElement(d).id).set_value(e)):(c.toLowerCase(),h.findElement(d).value=e))}catch(k){}}}
function RadGridIsNotNullAllControl(a,b,d,c){a=$find(a).get_masterTableView();if(null!=a){var e=a.get_dataItems().length;if(0<e){var f;for(i=0;i<e;i++){f=a.get_dataItems()[i];var g=f.findElement(b);if(!1==g.disabled&&!0==g.checked)if(f=f.findElement(d),null!=f.type)if("text"==f.type.toLowerCase()||"textarea"==f.type.toLowerCase()||"password"==f.type.toLowerCase()){if(""==f.value)return null!=c&&GetAlertError(iTotal,DSAlert,c),f.focus(),!1}else{if(null!=f.type.tolowercase().match("select")&&""==f.options[f.selectedindex].value)return null!=
c&&GetAlertError(iTotal,DSAlert,c),f.focus(),!1}else if(f=$find(f.id),-1!=Object.getTypeName(f).indexOf("RadComboBox")&&""==f.get_value())return GetAlertError(iTotal,DSAlert,c),f.get_inputDomElement().focus(),!1}}}return!0}
function RadGridIsNotNullAllControl_NotFocus(a,b,d,c){a=$find(a).get_masterTableView();if(null!=a){var e=a.get_dataItems().length;if(0<e){var f;for(i=0;i<e;i++){f=a.get_dataItems()[i];var g=f.findElement(b);if(!1==g.disabled&&!0==g.checked)if(f=f.findElement(d),null!=f.type)if("text"==f.type.toLowerCase()||"textarea"==f.type.toLowerCase()||"password"==f.type.toLowerCase()){if(""==f.value)return null!=c&&GetAlertError(iTotal,DSAlert,c),!1}else{if(null!=f.type.tolowercase().match("select")&&""==f.options[f.selectedindex].value)return null!=
c&&GetAlertError(iTotal,DSAlert,c),!1}else if(f=$find(f.id),-1!=Object.getTypeName(f).indexOf("RadComboBox")&&""==f.get_value())return GetAlertError(iTotal,DSAlert,c),!1}}}return!0}
function RadGridIsNotNullAllControl_(a,b,d,c,e){a=$find(a).get_masterTableView();if(null!=a){var f=a.get_dataItems().length;if(0<f){var g;for(i=0;i<f;i++){var h=a.get_dataItems()[i];g=h.findElement(b);if(!1==g.disabled&&!0==g.checked)if(g=h.findElement(d),null!=g.type)if("text"==g.type.toLowerCase()||"textarea"==g.type.toLowerCase()){if(""==g.value)return null!=e&&GetAlertError(iTotal,DSAlert,e),g=h.findElement(c),g.focus(),!1}else{if(null!=g.type.tolowercase().match("select")&&""==g.options[g.selectedindex].value)return null!=
e&&GetAlertError(iTotal,DSAlert,e),g=h.findElement(c),g.focus(),!1}else if(g=$find(g.id),-1!=Object.getTypeName(g).indexOf("RadComboBox")&&""==g.get_value())return GetAlertError(iTotal,DSAlert,e),g=h.findElement(c),g.focus(),!1}}}return!0}
function RadGridFromSmallOrEqualToMonth(a,b,d,c,e,f,g){a=$find(a).get_masterTableView();if(null!=a){var h=a.get_dataItems().length;if(0<h){var j,k;for(i=0;i<h;i++)if(k=a.get_dataItems()[i],j=k.findElement(b),!1==j.disabled&&!0==j.checked){j=k.findElement(d);k=k.findElement(c);if(!0==f&&null!=j.type&&"text"==j.type.toLowerCase()&&""==j.value)return null!=e&&GetAlertError(iTotal,DSAlert,e),j.focus(),!1;if(!0==g&&null!=k.type&&"text"==k.type.toLowerCase()&&""==k.value)return null!=e&&GetAlertError(iTotal,
DSAlert,e),k.focus(),!1;if(""!=j.value&&""!=k.value&&!1==FromSmallOrEqualToMonth(j,k))return GetAlertError(iTotal,DSAlert,"0007"),j.focus(),!1}}}return!0}
function RadGridFromSmallOrEqualToDate(a,b,d,c,e,f,g){a=$find(a).get_masterTableView();if(null!=a){var h=a.get_dataItems().length;if(0<h){var j,k;for(i=0;i<h;i++)if(k=a.get_dataItems()[i],j=k.findElement(b),!1==j.disabled&&!0==j.checked){j=k.findElement(d);k=k.findElement(c);if(!0==f&&null!=j.type&&"text"==j.type.toLowerCase()&&""==j.value)return null!=e&&GetAlertError(iTotal,DSAlert,e),j.focus(),!1;if(!0==g&&null!=k.type&&"text"==k.type.toLowerCase()&&""==k.value)return null!=e&&GetAlertError(iTotal,
DSAlert,e),k.focus(),!1;if(""!=j.value&&""!=k.value&&!1==FromSmallOrEqualToDate(j,k))return GetAlertError(iTotal,DSAlert,"01111"),k.focus(),!1}}}return!0}
function RadGridFromSmallOrEqualToDate2(a,b,d,c,e,f){a=$find(a).get_masterTableView();if(null!=a){var g=a.get_dataItems().length;if(0<g){var h,j;for(i=0;i<g;i++)if(j=a.get_dataItems()[i],h=j.findElement(b),!1==h.disabled&&!0==h.checked){h=j.findElement(d);j=j.findElement(c);if(!0==e&&null!=h.type&&"text"==h.type.toLowerCase()&&""==h.value)return GetAlertError(iTotal,DSAlert,"0003"),h.focus(),!1;if(!0==f&&null!=j.type&&"text"==j.type.toLowerCase()&&""==j.value)return GetAlertError(iTotal,DSAlert,"0003"),
j.focus(),!1;if(""!=h.value&&""!=j.value&&!1==FromSmallOrEqualToDate(h,j))return GetAlertError(iTotal,DSAlert,"0007"),j.focus(),!1}}}return!0}
function RadGridFillTextBox(a,b,d,c,e){a=$find(a).get_masterTableView();if(null!=a){var f=a.get_dataItems().length;if(0<f){var g,h;for(i=0;i<f;i++)h=a.get_dataItems()[i],g=h.findElement(b),!1==g.disabled&&!0==g.checked&&(g=h.findElement(d),h=h.findElement(c),null!=g.type&&"text"==g.type.toLowerCase()&&(!0==e?h.value=g.value:""!=g.value&&(h.value=g.value)))}}return!1}
function GridCheck_RadGrid(a,b){if(!1==RowCheck_RadGrid(a.replace("_ctl0_","")))return!1;var d,c,e,f=$find(a).get_masterTableView();if(null!=f&&(c=f.get_dataItems().length,e=!0,0<c))for(d=0;d<c;d++){var g=f.get_dataItems()[d].findElement(b);if(null!=g&&!0==g.checked){e=!1;break}}return e?!1:!0}function GridReadOnly_RadGrid(a,b){var d,c,e=$find("_ctl0_"+a).get_masterTableView();if(null!=e&&(c=e.get_dataItems().length,0<c))for(d=0;d<c;d++)e.get_dataItems()[d].findElement(b).readOnly=!0;return!0}
function GridReadOnly(a,b,d,c,e){var f;f=document.getElementById(a).rows.length;NoItemCheck=!0;if(1<f)for(;b<document.getElementById(a).rows.length+d;b++)document.getElementById(a+"__ctl"+b+"_"+c).readOnly=e;return!0}function GridDisable(a,b,d,c,e){var f;f=document.getElementById(a).rows.length;NoItemCheck=!0;if(1<f)for(;b<document.getElementById(a).rows.length+d;b++)document.getElementById(a+"__ctl"+b+"_"+c).disabled=e;return!0}
function GridNoHeaderCheck(a,b,d,c){var e,f;e=document.getElementById(a).rows.length;f=!0;if(0<e)for(;b<document.getElementById(a).rows.length+d;b++)if(!0==document.getElementById(a+"__ctl"+b+"_"+c).checked){f=!1;break}return f?!1:!0}
function CheckAll(a,b,d,c,e){a=document.getElementById(a).checked;if(null!=document.getElementById(b)&&(count=document.getElementById(b).rows.length,1<count))for(;d<document.getElementById(b).rows.length+c;d++)document.all&&!document.getElementByID?!0!=document.Form1(b+"__ctl"+d+"_"+e).disabled&&(document.Form1(b+"__ctl"+d+"_"+e).checked=a):document.getElementById(b+"__ctl"+d+"_"+e).disabled||(document.getElementById(b+"__ctl"+d+"_"+e).checked=a)}
function CheckAll_RadGrid(a,b,d){try{var c=document.getElementById(a).checked,e,f=$find(b).get_masterTableView();if(null!=f&&(count=f.get_dataItems().length,0<count))for(e=0;e<count;e++){var g=f.get_dataItems()[e].findElement(d);!1==g.disabled&&(g.checked=c)}}catch(h){}}function Clear_RadGrid(a){a=document.getElementById("_ctl0_"+a+"ctl0");if(null==a)return!1;var b=a.rows[0].cells.length;a.insertRow(0).insertCell(0).colspan=b;for(i=a.rows.length-1;1<=i;i--)a.deleteRow(i)}
function Clear_Grid(a){a=document.getElementById("_ctl0_"+a);if(null==a)return!1;for(i=a.rows.length-1;0<i;i--)a.deleteRow(i);null!=document.getElementById("_ctl0_uctrlColumns_lblTotalRow")&&(document.getElementById("_ctl0_uctrlColumns_lblTotalRow").innerHTML="0")}function RowCheck_RadGrid(a){a=document.getElementById("_ctl0_"+a+"ctl0");if(null==a||0>a.rows.length-1)return!1}
function CheckAllWithClick(a,b,d,c,e){a=document.getElementById(a).checked;if(null!=document.getElementById(b)&&(count=document.getElementById(b).rows.length,1<count))for(;d<document.getElementById(b).rows.length+c;d++)!0!=document.Form1(b+"__ctl"+d+"_"+e).disabled&&(document.Form1(b+"__ctl"+d+"_"+e).click(),document.Form1(b+"__ctl"+d+"_"+e).checked=a)}function trim(a){a=a.replace(/^(\s)+/,"");return a=a.replace(/(\s)+$/,"")}
function checkKey(a){13==window.event.keyCode&&(null!=document.getElementById(a)&&document.getElementById(a).click(),event.returnValue=!1,event.cancel=!0)}function checkKey(a,b){if(13==(window.event?event.keyCode:b.which)&&null!=document.getElementById(a))if(window.event)document.getElementById(a).click(),event.returnValue=!1,event.cancel=!0;else{var d=document.getElementById(a);"function"==typeof d.onclick&&d.onclick.apply(d)}}
function checkBit(a){if(0!=a.value&&1!=a.value)return GetAlertError(iTotal,DSAlert,"0051"),a.value="",a.focus(),!1}function CheckOT(a){if(""!=a.value){var b=a.value.replace(/,/g,"");if(isNaN(b))GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus();else if(0>b)GetAlertError(iTotal,DSAlert,"0012"),a.value="",a.focus();else{if(1>a.value||60<a.value)return GetAlertError(iTotal,DSAlert,"TSPR_0004"),a.value="",a.focus(),!1;FormatNumericWithSeparate(a)}}}
function checkScanCheck(a){if(""!=a.value){var b=a.value.replace(/,/g,"");if(isNaN(b))GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus();else if(0>b)GetAlertError(iTotal,DSAlert,"0012"),a.value="",a.focus();else{if(2!=a.value&&4!=a.value&&6!=a.value)return GetAlertError(iTotal,DSAlert,"TSPR_0001"),a.value="",a.focus(),!1;FormatNumericWithSeparate(a)}}}
function checkStandardDays(a){if(""!=a.value){var b=a.value.replace(/,/g,"");if(isNaN(b))GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus();else if(0>b)GetAlertError(iTotal,DSAlert,"0012"),a.value="",a.focus();else{if(1>a.value||30<a.value)return GetAlertError(iTotal,DSAlert,"TSPR_0002"),a.value="",a.focus(),!1;FormatNumericWithSeparate(a)}}}
function checkHourday(a){if(null!=a&&""!=a.value){var b=a.value.replace(/,/g,"");if(isNaN(b))GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus();else if(0>b)GetAlertError(iTotal,DSAlert,"0012"),a.value="",a.focus();else{if(1>a.value||24<a.value)return GetAlertError(iTotal,DSAlert,"TSPR_0003"),a.value="",a.focus(),!1;FormatNumericWithSeparate(a)}}}
function checkNumeric(a,b){if(null!=a&&""!=a.value){var d;d=/,/g;var c=a.value.replace(d,"");d=/\s+/;c=c.replace(d,"");if(""==c)a.value="";else{if(isNaN(c))return GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus(),!1;if(0>c)return GetAlertError(iTotal,DSAlert,"00012"),a.value="",a.focus(),!1;if(c>b)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0054").replace("@",b)),a.value="",a.focus(),!1;FormatNumericWithSeparate(a)}}}
function checkNumericButton(a,b,d){if(null!=a){if(""==a.value)return GetAlertError(iTotal,DSAlert,"0003"),a.focus(),document.getElementById(d).disabled=!0,!1;var c=a.value.replace(/,/g,"");if(isNaN(c))return GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus(),document.getElementById(d).disabled=!0,!1;if(0>c)return GetAlertError(iTotal,DSAlert,"0012"),a.value="",a.focus(),document.getElementById(d).disabled=!0,!1;if(c>b)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0054").replace("@",
b)),a.focus(),document.getElementById(d).disabled=!0,!1;document.getElementById(d).disabled=!1;FormatNumericWithSeparate(a)}}function checkNumeric1(a){if(null!=a&&""!=a.value){var b=a.value.replace(/,/g,"");isNaN(b)?(GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus()):0>=b?(GetAlertError(iTotal,DSAlert,"0012"),a.value="",a.focus()):FormatNumericWithSeparate(a)}}
function checkNumber(a){if(""==a.value)return!1;var b=a.value.replace(/,/g,"");if(isNaN(b))return GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus(),!1;FormatNumericWithSeparate(a)}function checkNumericNotSeparate(a){if(""!=a.value){var b=a.value.replace(/,/g,"");isNaN(b)?(GetAlertError(iTotal,DSAlert,"0009"),a.value="",a.focus()):0>b&&(GetAlertError(iTotal,DSAlert,"0035"),a.value="",a.focus())}}
function EditInput(a){var b=a.selectionStart,d=ReplaceMoneyNumeric(a);a.value=d;a.SelectionStart=b}function ReplaceMoneyNumeric(a){return a.value.replace(/,/g,"")}function ReplaceMoneyNumericFromValue(a){return a.replace(/,/g,"")}
function FormatNumericWithSeparate(a){var b=parseFloat(a.value.replace(/,/g,"")).toString(),d="",c="";0>b&&(b=b.substring(1,b.length));-1!=b.indexOf(".")&&(d=b.substring(b.indexOf("."),b.indexOf(".")+2+1),b=b.substring(0,b.indexOf(".")));if(-1!=d.indexOf(","))GetAlertError(iTotal,DSAlert,"0035"),a.value="",a.focus();else{b=b.replace(/,/g,"");for(c="";3<b.length;)c=","+b.substring(b.length-3,b.length)+c,b=b.substring(0,b.length-3);c=b+c+d;0>parseFloat(a.value.replace(/,/g,""))&&(c="-"+c);a.value=c}}
function FormatNumericWithSeparateValue(a){var b=a.toString(),d="",c="";0>b&&(b=b.substring(1,b.length));-1!=b.indexOf(".")&&(d=b.substring(b.indexOf("."),b.indexOf(".")+2+1),b=b.substring(0,b.indexOf(".")));if(-1!=d.indexOf(","))GetAlertError(iTotal,DSAlert,"0035");else{b=b.replace(/,/g,"");for(c="";3<b.length;)c=","+b.substring(b.length-3,b.length)+c,b=b.substring(0,b.length-3);c=b+c+d;0>a&&(c="-"+c);return c}}
function FormatNumericWithSeparate_Decimal(a,b){b=CheckFloat(b);var d=parseFloat(a.value.replace(/,/g,"")).toString(),c="",e="";0>d&&(d=d.substring(1,d.length));-1!=d.indexOf(".")&&(c=d.substring(d.indexOf("."),d.indexOf(".")+b+1),d=d.substring(0,d.indexOf(".")));if(-1!=c.indexOf(","))GetAlertError(iTotal,DSAlert,"0035"),a.value="",a.focus();else{d=d.replace(/,/g,"");for(e="";3<d.length;)e=","+d.substring(d.length-3,d.length)+e,d=d.substring(0,d.length-3);e=d+e+c;0>parseFloat(a.value.replace(/,/g,
""))&&(e="-"+e);a.value=e;return!1}}
function checkNumeric_Decimal(a,b,d){d=CheckFloat(d);if(null!=a&&""!=a.value){var c;c=/,/g;var e=a.value.replace(c,"");c=/\s+/;e=e.replace(c,"");if(""==e)a.value="";else{if(isNaN(e))return GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus(),!1;if(0>e)return GetAlertError(iTotal,DSAlert,"00012"),a.value="",a.focus(),!1;if(e>b)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0054").replace("@",b)),a.value="",a.focus(),!1;FormatNumericWithSeparate_Decimal(a,d)}}}
function checkNumber_Decimal(a,b){b=CheckFloat(b);if(null!=a&&""!=a.value){var d;d=/,/g;var c=a.value.replace(d,"");d=/\s+/;c=c.replace(d,"");if(""==c)a.value="";else{if(isNaN(c))return GetAlertError(iTotal,DSAlert,"0013"),a.value="",a.focus(),!1;FormatNumericWithSeparate_Decimal(a,b)}}}
function checkNoRound05(a,b){if(""==a.value)return!0;var d=a.value.replace(/,/g,"");return isNaN(d)||0>=d?(GetAlertError(iTotal,DSAlert,"0035"),a.value="",a.focus(),!1):Math.round(parseFloat(d)/0.5)!=parseFloat(d)/0.5?(GetAlertError(iTotal,DSAlert,"0036"),a.value="",a.focus(),!1):d>=b?(GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0054").replace("@",b)),a.focus(),!1):!0}
function checkNoRound05(a){if(""==a.value)return!0;var b=a.value.replace(/,/g,"");return isNaN(b)||0>b?(GetAlertError(iTotal,DSAlert,"0035"),a.value="",a.focus(),!1):Math.round(parseFloat(b)/0.5)!=parseFloat(b)/0.5?(GetAlertError(iTotal,DSAlert,"0036"),a.value="",a.focus(),!1):!0}
function DaycheckNoRound05(a){if(""==a.value)return!0;var b=a.value;if(isNaN(b))return GetAlertError(iTotal,DSAlert,"0037"),a.value="0",a.focus(),!1;if(0!=parseFloat(b)&&0.5!=parseFloat(b)&&1!=parseFloat(b))return GetAlertError(iTotal,DSAlert,"0038"),a.value="0",a.focus(),!1;a.value=parseFloat(b);return!0}
function CheckPercent(a){if(""!=a.value){var b=a.value;if(isNaN(b))GetAlertError(iTotal,DSAlert,"0037"),a.value="",a.focus();else if(0>b||100<b)GetAlertError(iTotal,DSAlert,"0039"),a.value="",a.focus()}}function checkInteger(a){a.value=ReplaceMoneyNumeric(a);var b=a.value;if(isNaN(b))return GetAlertError(iTotal,DSAlert,"0040"),a.focus(),a.value="",!1;if(0>b)return GetAlertError(iTotal,DSAlert,"0010"),a.focus(),a.value="",!1;a.value=Math.round(a.value);return!0}
function RoundMoney(a){a=parseFloat(ReplaceMoneyNumericFromValue(a));return FormatNumericWithSeparateValue(Math.round(a))}function checkInteger(a){if(""==a.value)return!0;a.value=ReplaceMoneyNumeric(a);var b=a.value;if(isNaN(b))return GetAlertError(iTotal,DSAlert,"0040"),a.focus(),a.value="",!1;if(0>b)return GetAlertError(iTotal,DSAlert,"0010"),a.focus(),a.value="",!1;a.value=Math.round(a.value);FormatNumericWithSeparate(a);return!0}
function checkInt(a,b){var d=a.value;if(""!=d){if(isNaN(d))return GetAlertError(iTotal,DSAlert,"0040"),a.focus(),a.value="",!1;if(1>d)return GetAlertError(iTotal,DSAlert,"0072"),a.focus(),a.value="",!1;if(d>b)return GetAlertTextPopUp(GetAlertText(iTotal,DSAlert,"0054").replace("@",b)),a.focus(),!1;a.value=Math.round(a.value);FormatNumericWithSeparate(a);return!0}}
function roundNumber(a,b){var d=a;return d=8191<d&&10485>d?Math.round((d-5E3)*Math.pow(10,b))/Math.pow(10,b):Math.round(d*Math.pow(10,b))/Math.pow(10,b)}function roundNumberNew(a,b){var d=parseFloat(a),c=parseFloat(b),d=Math.round(d*Math.pow(10,c))/Math.pow(10,c);return-5==c?Math.round(d):d}function DeltaHourToHour(a,b){var d,c,e,f;e=a.value;f=b.value;d=e.substring(0,2);c=e.substring(3,5);e=f.substring(0,2);f=f.substring(3,5);d=60*eval(d)+eval(c);return 60*eval(e)+eval(f)-d}
function checkOfficeHours(a,b){if(1==b)return!0;var d,c;c=a.value;var e;d=c.substring(0,2);c=c.substring(3,5);d=60*eval(d)+eval(c);c=60*eval("08")+eval("30");e=60*eval("17")+eval("30");return c<d&&d<e?(GetAlertError(iTotal,DSAlert,"OT_0004"),a.focus(),!1):!0}
function formatHours(a){var b,d,c,e;b=d="";b=a.value;if(0==b.length)return a.value="",!1;for(c=0;c<b.length;c++)0<="0123456789".indexOf(b.substr(c,1))&&(d+=b.substr(c,1));if(4!=d.length)return a.value="",!1;b=d.substring(0,2);d=d.substring(2,4);if(isNaN(b)||isNaN(d))return a.value="",!1;c=parseInt(b,10);e=parseInt(d,10);if(0>c||0>e||24<=c||60<=e)return a.value="",!1;a.value=b+":"+d;return!0}
function AddMinuteToHours(a,b){var d,c,e,f;d=a.substring(0,2);c=a.substring(3,5);if(isNaN(d)||isNaN(c))return"";d=parseInt(d,10);c=parseInt(c,10);if(0>d||0>c||24<=d||60<=c)return"";e=Math.floor(b/60);f=b-60*e;if(60<=c+f){var g=Math.floor((c+f)/60);c=c+f-60*g;d+=g}else c+=f;d+=e;24<=d&&(d-=24*Math.floor(d/24));d=10>d?"0"+d.toString():d.toString();c=10>c?"0"+c.toString():c.toString();return d+":"+c}
function CompareHours(a,b){sHour1=parseFloat(a.value.substring(0,2));sMinute1=parseFloat(a.value.substring(3,5));sHour2=parseFloat(b.value.substring(0,2));sMinute2=parseFloat(b.value.substring(3,5));value1=60*sHour1+sMinute1;value2=60*sHour2+sMinute2;if(value1==value2)return 0;if(value1>value2)return 1;if(value1<value2)return-1}
function CompareHoursValue(a,b){sHour1=parseFloat(a.substring(0,2));sMinute1=parseFloat(a.substring(3,5));sHour2=parseFloat(b.substring(0,2));sMinute2=parseFloat(b.substring(3,5));a=60*sHour1+sMinute1;b=60*sHour2+sMinute2;if(a==b)return 0;if(a>b)return 1;if(a<b)return-1}
function CheckYear(a){var b="",d="",c,b=a.value;if(0!=b.length){for(c=0;c<b.length;c++)0<="0123456789".indexOf(b.substr(c,1))&&(d+=b.substr(c,1));b=d;2==b.length&&(b="20"+b);if(4!=b.length&&0!=b.length||0==b)GetAlertError(iTotal,DSAlert,"0041"),a.focus();a.value=b}}
function CheckYear1900(a){var b="",d="",c,b=a.value;if(0!=b.length){for(c=0;c<b.length;c++)0<="0123456789".indexOf(b.substr(c,1))&&(d+=b.substr(c,1));b=d;2==b.length&&(b="20"+b);if(4!=b.length&&0!=b.length||0==b)GetAlertError(iTotal,DSAlert,"0041"),a.focus();a.value=b;1900>a.value&&(GetAlertError(iTotal,DSAlert,"1239"),a.focus())}}
function CheckMonth(a){var b="",d="",c,b=a.value;if(0!=b.length){for(c=0;c<b.length;c++)0<="0123456789".indexOf(b.substr(c,1))&&(d+=b.substr(c,1));b=d;if(12<b||1>b)GetAlertError(iTotal,DSAlert,"0094"),a.focus();1==b.length&&(b="0"+b);a.value=b}}
function CheckMonthYear(a){var b="",d="/",c,e=0,e=0;DateValue=a.value;if(""!=DateValue){for(c=0;c<DateValue.length;c++)0<="0123456789".indexOf(DateValue.substr(c,1))&&(b+=DateValue.substr(c,1));DateValue=b;4==DateValue.length&&(DateValue=DateValue.substr(0,2)+"20"+DateValue.substr(2,2));6!=DateValue.length&&(e=19);c=DateValue.substr(2,4);0==c&&(e=20);b=DateValue.substr(0,2);if(1>b||12<b)e=21;0==b&&0==c&&(e=0,d=c=b="");if(0==e){if(a.value=b+d+c,""==a.value)return GetAlertError(iTotal,DSAlert,"0042"),
a.focus(),!1}else return a.value="",a.focus(),GetAlertError(iTotal,DSAlert,"0042"),!1}}
function CheckDate(a){var b="",d="/",c,e,f=0,g=0,g=0;DateValue=a.value;for(c=0;c<DateValue.length;c++)0<="0123456789".indexOf(DateValue.substr(c,1))&&(b+=DateValue.substr(c,1));DateValue=b;6==DateValue.length&&(DateValue=DateValue.substr(0,4)+"20"+DateValue.substr(4,2));8!=DateValue.length&&(g=19);e=DateValue.substr(4,4);0==e&&(g=20);b=DateValue.substr(0,2);c=DateValue.substr(2,2);if(1>c||12<c)g=21;1900>=e&&(g=18);1>b&&(g=22);if(0==e%4||0==e%100||0==e%400)f=1;2==c&&(1==f&&29<b)&&(g=23);2==c&&(1!=
f&&28<b)&&(g=24);if(31<b&&("01"==c||"03"==c||"05"==c||"07"==c||"08"==c||"10"==c||"12"==c))g=25;if(30<b&&("04"==c||"06"==c||"09"==c||"11"==c))g=26;0==b&&(0==c&&0==e)&&(g=0,d=e=c=b="");if(0==g)return a.value=b+d+c+d+e,!0;18==g?(a.value="",a.focus(),GetAlertError(iTotal,DSAlert,"0030")):(a.value="",a.focus(),GetAlertError(iTotal,DSAlert,"0031"));return!1}
function CheckDateValue(a){var b="",d,c=0,e=0;for(d=e=0;d<a.length;d++)0<="0123456789".indexOf(a.substr(d,1))&&(b+=a.substr(d,1));a=b;6==a.length&&(a=a.substr(0,4)+"20"+a.substr(4,2));8!=a.length&&(e=19);d=a.substr(4,4);0==d&&(e=20);b=a.substr(0,2);a=a.substr(2,2);if(1>a||12<a)e=21;1900>=d&&(e=18);1>b&&(e=22);if(0==d%4||0==d%100||0==d%400)c=1;2==a&&(1==c&&29<b)&&(e=23);2==a&&(1!=c&&28<b)&&(e=24);if(31<b&&("01"==a||"03"==a||"05"==a||"07"==a||"08"==a||"10"==a||"12"==a))e=25;if(30<b&&("04"==a||"06"==
a||"09"==a||"11"==a))e=26;0==b&&(0==a&&0==d)&&(e=0);return 0==e?!0:!1}
function CheckDDMM(a){var b="",d="/",c,e,f=0,g=0,g=0;DateValue=""!=a.value?a.value+"/2006":a.value;for(c=0;c<DateValue.length;c++)0<="0123456789".indexOf(DateValue.substr(c,1))&&(b+=DateValue.substr(c,1));DateValue=b;6==DateValue.length&&(DateValue=DateValue.substr(0,4)+"20"+DateValue.substr(4,2));8!=DateValue.length&&(g=19);e=DateValue.substr(4,4);0==e&&(g=20);c=DateValue.substr(2,2);if(1>c||12<c)g=21;b=DateValue.substr(0,2);1900>=e&&(g=18);1>b&&(g=22);if(0==e%4||0==e%100||0==e%400)f=1;2==c&&(1==
f&&29<b)&&(g=23);2==c&&(1!=f&&29<b)&&(g=24);if(31<b&&("01"==c||"03"==c||"05"==c||"07"==c||"08"==c||"10"==c||"12"==c))g=25;if(30<b&&("04"==c||"06"==c||"09"==c||"11"==c))g=26;0==b&&(0==c&&0==e)&&(g=0,d=c=b="");if(0==g)return a.value=b+d+c,!0;a.value="";a.focus();GetAlertError(iTotal,DSAlert,"2010");return!1}function addDays(a,b){return new Date(a.getTime()+864E5*b)}
function addDays2(a,b){var d=a.substr(0,2),c=a.substr(3,2),e=a.substr(6,4),e=new Date(c+"/"+d+"/"+e);e.setDate(e.getDate()+parseInt(b));d=10>e.getDate()?"0"+e.getDate().toString():e.getDate().toString();c=10>e.getMonth()+1?"0"+(e.getMonth()+1).toString():(e.getMonth()+1).toString();e=e.getFullYear().toString();return d+"/"+c+"/"+e}
function AddDaystoDateFull(a,b){var d,c;d=new Date(ConvertMMDDYYYY(a));c=new Date(d.getTime()+864E5*b);d=new String(c.getDate());d="0"+d;d=d.substring(d.length,d.length-2);var e=new String(c.getMonth()+1),e="0"+e,e=e.substring(e.length,e.length-2);c=new String(c.getFullYear());return strDate=d+"/"+e+"/"+c}
function AddDaystoDate(a,b){var d=a.substr(0,2),c=a.substr(3,2),e=a.substr(6,4),f,d=parseFloat(d)+parseFloat(b);if(0>b){0>=d&&(c=parseFloat(c)-1);0==parseFloat(c)&&(c=12,e=parseFloat(e)-1);if(0==e%4||0==e%100||0==e%400)f=1;if(2==c&&1==f&&0>=d)d=parseFloat(d)+29;else if(2==c&&1!=f&&0>=d)d=parseFloat(d)+28;else if(0>=d&&("01"==c||"03"==c||"05"==c||"07"==c||"08"==c||"10"==c||"12"==c))d=parseFloat(d)+31;else if(0>=d&&("04"==c||"06"==c||"09"==c||"11"==c))d=parseFloat(d)+30}else{if(0==e%4||0==e%100||0==
e%400)f=1;if(2==c&&1==f&&29<d)c=parseFloat(c)+1,12<c&&(c=1,e=parseFloat(e)+1),d=parseFloat(d)-29;else if(2==c&&1!=f&&28<d)c=parseFloat(c)+1,12<c&&(c=1,e=parseFloat(e)+1),d=parseFloat(d)-28;else if(31<d&&("01"==c||"03"==c||"05"==c||"07"==c||"08"==c||"10"==c||"12"==c))c=parseFloat(c)+1,12<c&&(c=1,e=parseFloat(e)+1),d=parseFloat(d)-31;else if(30<d&&("04"==c||"06"==c||"09"==c||"11"==c))c=parseFloat(c)+1,12<c&&(c=1,e=parseFloat(e)+1),d=parseFloat(d)-30}1==d.toString().length&&(d="0"+d);1==c.toString().length&&
(c="0"+c);return d+"/"+c+"/"+e}
function AddMonthstoDate(a,b){var d=a.substr(0,2),c=a.substr(3,2),e=a.substr(6,4),f;b=parseFloat(b);for(var c=parseFloat(c)+parseFloat(b),g=0;0<c-12;)g=parseFloat(g)+1,c-=12;e=parseFloat(e)+g;if(0==e%4||0==e%100||0==e%400)f=1;if(2==c&&1==f&&29<d)d=29;else if(2==c&&1!=f&&28<d)d=28;else if(31<=d&&("01"==c||"03"==c||"05"==c||"07"==c||"08"==c||"10"==c||"12"==c))d=31;else if(30<d&&("04"==c||"06"==c||"09"==c||"11"==c))d=30;1==(d+"").length&&(d="0"+d);1==(c+"").length&&(c="0"+c);return d+"/"+c+"/"+e}
function AddYearstoDate(a,b){var d=a.substr(0,2),c=a.substr(3,2),e=a.substr(6,4);b=parseFloat(b);e=parseFloat(e)+parseFloat(b);1==d.length&&(d="0"+d);1==c.length&&(c="0"+c);return d+"/"+c+"/"+e}function ConvertMMDDYYYY(a){if(!1!=CheckDate(a)){var b,d;a=a.value;d="";for(b=0;b<a.length;b++)0<="0123456789".indexOf(a.substr(b,1))&&(d+=a.substr(b,1));a=d;d=a.substr(4,4);b=a.substr(2,2);a=a.substr(0,2);return b+"/"+a+"/"+d}}
function DeltaTwoDay(a,b){if(!(""==a||""==b)){var d,c="",e="";for(d=0;d<a.length;d++)0<="0123456789".indexOf(a.substr(d,1))&&(c+=a.substr(d,1));for(d=0;d<b.length;d++)0<="0123456789".indexOf(b.substr(d,1))&&(e+=b.substr(d,1));a=c;b=e;year1=a.substr(4,4);month1=a.substr(2,2);day1=a.substr(0,2);year2=b.substr(4,4);month2=b.substr(2,2);day2=b.substr(0,2);return(Date.UTC(parseInt(year2,10),parseInt(month2,10)-1,parseInt(day2,10))-Date.UTC(parseInt(year1,10),parseInt(month1,10)-1,parseInt(day1,10)))/864E5+
1}}
function DeltaDate1Date2(a,b){if(!1!=CheckDate(a)&&!1!=CheckDate(b)){var d=a.value,c=b.value;if(!(""==d||""==c)){var e,f="",g="";for(e=0;e<d.length;e++)0<="0123456789".indexOf(d.substr(e,1))&&(f+=d.substr(e,1));for(e=0;e<c.length;e++)0<="0123456789".indexOf(c.substr(e,1))&&(g+=c.substr(e,1));d=f;c=g;year1=d.substr(4,4);month1=d.substr(2,2);day1=d.substr(0,2);year2=c.substr(4,4);month2=c.substr(2,2);day2=c.substr(0,2);return(Date.UTC(parseInt(year2,10),parseInt(month2,10)-1,parseInt(day2,10))-Date.UTC(parseInt(year1,10),
parseInt(month1,10)-1,parseInt(day1,10)))/864E5+1}}}function IsSmaller(a,b){var d=a.indexOf("/"),c=a.lastIndexOf("/"),e=parseInt(a.substring(0,d),10),f=parseInt(a.substring(d+1,c),10),g=parseInt(a.substring(c+1,a.length),10),d=b.indexOf("/"),c=b.lastIndexOf("/");dd2=parseInt(b.substring(0,d),10);mm2=parseInt(b.substring(d+1,c),10);yyyy2=parseInt(b.substring(c+1,b.length),10);return yyyy2>g?!0:yyyy2==g?mm2==f?dd2>e?!0:!1:mm2>f?!0:!1:!1}
function IsSmallerOrEqual(a,b){var d=a.indexOf("/"),c=a.lastIndexOf("/"),e=parseInt(a.substring(0,d),10),f=parseInt(a.substring(d+1,c),10),g=parseInt(a.substring(c+1,a.length),10),d=b.indexOf("/"),c=b.lastIndexOf("/");dd2=parseInt(b.substring(0,d),10);mm2=parseInt(b.substring(d+1,c),10);yyyy2=parseInt(b.substring(c+1,b.length),10);return yyyy2>g?!0:yyyy2==g?mm2==f?dd2>=e?!0:!1:mm2>f?!0:!1:!1}
function MonthOfDate(a){var b=a.indexOf("/"),d=a.lastIndexOf("/");parseInt(a.substring(0,b),10);b=parseInt(a.substring(b+1,d),10);a=parseInt(a.substring(d+1,a.length),10);return b+"/"+a}function FromSmallToDate(a,b){FromDate=a.value;ToDate=b.value;return!isBlank(FromDate)&&!isBlank(ToDate)?IsSmaller(FromDate,ToDate)?!0:!1:!0}function FromSmallOrEqualToDate(a,b){FromDate=a.value;ToDate=b.value;return!isBlank(FromDate)&&!isBlank(ToDate)?IsSmallerOrEqual(FromDate,ToDate)?!0:!1:!0}
function FromSmallOrEqualToDateValue(a,b){return!isBlank(a)&&!isBlank(b)?IsSmallerOrEqual(a,b)?!0:!1:!0}function FromSmallOrEqualToDate_ddMM(a,b){FromDate=a.value+"/2010";ToDate=b.value+"/2010";return!isBlank(FromDate)&&!isBlank(ToDate)?IsSmallerOrEqual(FromDate,ToDate)?!0:!1:!0}
function FromSmallNow(a){FromDate=a.value;var b=new Date;a=(b.getMonth()+1).toString();var d=b.getDate().toString(),d=parseInt(d)+1,b=b.getFullYear().toString();ToDate=d+"/"+a+"/"+b;return!isBlank(FromDate)&&!isBlank(ToDate)?IsSmaller(FromDate,ToDate)?!0:!1:!0}
function FromSmallNow1(a){FromDate=a.value;var b=new Date;a=(b.getMonth()+1).toString();var d=b.getDate().toString(),d=parseInt(d),b=b.getFullYear().toString();ToDate=d+"/"+a+"/"+b;return!isBlank(FromDate)&&!isBlank(ToDate)?IsSmaller(FromDate,ToDate)?!0:!1:!0}
function FromSmallNowMonth(a){FromDate="01/"+a.value;var b=new Date;a=(b.getMonth()+1).toString();var d=b.getDate().toString(),b=b.getFullYear().toString();ToDate=d+"/"+a+"/"+b;return!isBlank(FromDate)&&!isBlank(ToDate)?IsSmaller(FromDate,ToDate)?!0:!1:!0}function ToSmallNowMonth(){}function FromSmallToMonth(a,b){var d,c;c="01/"+a.value;d=""==b.value?"01/01/2100":"01/"+b.value;return!isBlank(c)&&!isBlank(d)?IsSmaller(c,d)?!0:!1:!0}
function FromSmallOrEqualToMonth(a,b){var d,c;c="01/"+a.value;d=""==b.value?"01/01/2100":"01/"+b.value;return!isBlank(c)&&!isBlank(d)?IsSmallerOrEqual(c,d)?!0:!1:!0}function FromSmallToMonth(a,b){var d,c;c="01/"+a.value;d=""==b.value?"01/01/2100":"01/"+b.value;return!isBlank(c)&&!isBlank(d)?IsSmaller(c,d)?!0:!1:!0}
function MonthOfDate(a){var b=a.indexOf("/"),d=a.lastIndexOf("/");parseInt(a.substring(0,b),10);b=parseInt(a.substring(b+1,d),10);a=parseInt(a.substring(d+1,a.length),10);return b+"/"+a}function FromSmallToMonthValue(a,b){var d,c;c="01/"+a;d=""==b?"01/01/2100":"01/"+b;return!isBlank(c)&&!isBlank(d)?IsSmallerOrEqual(c,d)?!0:!1:!0}
function CheckQuarter(a){if(!1==checkNumeric(a))return!1;value=a.value;if("1"!=value&&"2"!=value&&"3"!=value&&"4"!=value)return GetAlertError(iTotal,DSAlert,"0043"),a.focus(),!1}function Confirm_Delete(){return confirm("D\u00f2ng \u0111\u01b0\u1ee3c ch\u1ecdn s\u1ebd b\u1ecb xo\u00e1?")?!0:!1}
function EmailCheck(a){emailStr=a.value;if(""==emailStr)return!0;var b=emailStr.match(/^(.+)@(.+)$/);if(null==b)return GetAlertError(iTotal,DSAlert,"00005"),a.focus(),!1;var d=b[2];if(null==b[1].match(/^([^\s\(\)<>@,;:\\\"\.\[\]]+|("[^"]*"))(\.([^\s\(\)<>@,;:\\\"\.\[\]]+|("[^"]*")))*$/))return GetAlertError(iTotal,DSAlert,"00006"),a.focus(),!1;b=d.match(/^\[(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})\]$/);if(null!=b){for(d=1;4>=d;d++)if(255<b[d])return GetAlertError(iTotal,DSAlert,"00007"),a.focus(),
!1;return!0}if(null==d.match(/^[^\s\(\)<>@,;:\\\"\.\[\]]+(\.[^\s\(\)<>@,;:\\\"\.\[\]]+)*$/))return GetAlertError(iTotal,DSAlert,"00008"),a.focus(),!1;d=d.match(RegExp('[^\\s\\(\\)<>@,;:\\\\\\"\\.\\[\\]]+',"g"));b=d.length;return 2>d[d.length-1].length||3<d[d.length-1].length?(GetAlertError(iTotal,DSAlert,"00009"),a.focus(),!1):2>b?(GetAlertError(iTotal,DSAlert,"00015"),a.focus(),!1):!0}
function ShowCalendar(a){document.all[a].value=window.showModalDialog("Calendar.htm",document.all[a].value,"dialogLeft:450px;dialogTop:300px;dialogHeight:210px;dialogWidth:265px;center:No;help:No;scroll:No;resizable:No;status:No;")}function CheckScanCode(a){5!=a.value.length&&0<a.value.length&&(GetAlertError(iTotal,DSAlert,"0055"),a.value="",a.focus())}
function CheckMonthYear(a){var b="",d="/",c,e=0,e=0;DateValue=a.value;if(""!=DateValue){for(c=0;c<DateValue.length;c++)0<="0123456789".indexOf(DateValue.substr(c,1))&&(b+=DateValue.substr(c,1));DateValue=b;4==DateValue.length&&(DateValue=DateValue.substr(0,2)+"20"+DateValue.substr(2,2));6!=DateValue.length&&(e=19);c=DateValue.substr(2,4);1900>c&&(e=20);0==c&&(e=20);b=DateValue.substr(0,2);if(1>b||12<b)e=21;0==b&&0==c&&(e=0,d=c=b="");0==e?(a.value=b+d+c,""==a.value&&(GetAlertError(iTotal,DSAlert,"0042"),
a.focus())):(a.value="",a.focus(),GetAlertError(iTotal,DSAlert,"0042"))}}
function ShowReport(a,b,d,c){t=screen.height-30;w=screen.width-10;b=GetParamReport(b);alert("http://localhost/iHRPCore/Reports/COMM_ReportGen.asp?report="+a+"&sql="+b+"&formula="+d+"&Value="+c);FileWindow=window.open("http://localhost/iHRPCore/Reports/COMM_ReportGen.asp?report="+a+"&sql="+b+"&formula="+d+"&Value="+c,"_blank","width="+w+", height="+t+", left=0, top=0, location=no, scrollbars=yes,resizable");FileWindow.focus();return!0}
function replaceChars(a){out=",";add="";for(temp=""+a;-1<temp.indexOf(out);)pos=temp.indexOf(out),temp=""+(temp.substring(0,pos)+add+temp.substring(pos+out.length,temp.length));return temp}function GetParamReport(a){for(i=0;i<window.document.forms(0).length-1;i++)obj=window.document.forms(0).item(i),-1!=a.indexOf(obj.id)&&""!=obj.id&&(a=a.replace(obj.id,"N["+obj.value));for(;-1!=a.indexOf('"');)a=a.replace('"',"'"),a=a.replace("'N[","N'");return a}
function GetThongBao(a){snMsg=a;snTitle="Th\u00f4ng b\u00e1o"}function GetAlertError(a,b,d){var c;for(c=0;c<=a;c++)if(b[0][c]==d){snMsg=b[1][c];snTitle="Th\u00f4ng b\u00e1o - Alert";document.getElementById("btnShow").onclick();break}return!1}function GetAlertError_Replace(a,b,d,c,e){var f;for(f=0;f<=a;f++)if(b[0][f]==d){snMsg=b[1][f];snMsg=snMsg.replace(c,e);snTitle="Th\u00f4ng b\u00e1o - Alert";document.getElementById("btnShow").onclick();break}return!1}
function GetAlertTextPopUp(a){snMsg=a;snTitle="Th\u00f4ng b\u00e1o - Alert";document.getElementById("btnShow").onclick()}function GetAlertText(a,b,d){var c;for(c=0;c<=a;c++)if(b[0][c]==d)return b[1][c]}function GetAlertText_Replace(a,b,d,c,e){for(var f="",f=0;f<=a;f++)if(b[0][f]==d)return f=b[1][f],f=f.replace(c,e)}var selectedList,availableList;function createListObjects(a,b){availableList=document.getElementById(b);selectedList=document.getElementById(a)}
function delAttribute(){for(var a,b=selectedList.length-1;0<=b;b--)if(!0==selectedList.options[b].selected){a=selectedList.options[b].index;if(0>a)return;availableList.appendChild(selectedList.options.item(a))}selectNone(selectedList,availableList);setSize(availableList,selectedList)}
function addAttribute(){for(var a,b=availableList.length-1;0<=b;b--)if(!0==availableList.options[b].selected){a=availableList.options[b].index;if(0>a)return;selectedList.appendChild(availableList.options.item(a))}selectNone(selectedList,availableList);setSize(selectedList,availableList)}function delAll(){for(i=selectedList.length-1;0<=i;i--)availableList.appendChild(selectedList.item(i));selectNone(selectedList,availableList);setSize(selectedList,availableList)}
function addAll(){for(i=availableList.length-1;0<=i;i--)selectedList.appendChild(availableList.item(i));selectNone(selectedList,availableList);setSize(selectedList,availableList)}function selectNone(a,b){a.selectedIndex=-1;selIndex=addIndex=b.selectedIndex=-1}function setSize(a,b){a.size=getSize(a);b.size=getSize(b)}function getSize(a){var b=a.childNodes.length,d=0;for(i=0;i<b;i++)1==a.childNodes.item(i).nodeType&&d++;return 2>d?2:d}
function showSelected(){var a=document.getElementById("selectedOptions").options,b="",d=a.length;for(i=0;i<d;i++)0<i&&(b+=","),b+=a.item(i).value;alert(b)}var selectedList2,availableList2;function createListObjects2(a,b){availableList2=document.getElementById(b);selectedList2=document.getElementById(a)}
function delAttribute2(){for(var a,b=selectedList2.length-1;0<=b;b--)if(!0==selectedList2.options[b].selected){a=selectedList2.options[b].index;if(0>a)return;availableList2.appendChild(selectedList2.options.item(a))}selectNone(selectedList2,availableList2);setSize(availableList2,selectedList2)}
function addAttribute2(){for(var a,b=availableList2.length-1;0<=b;b--)if(!0==availableList2.options[b].selected){a=availableList2.options[b].index;if(0>a)return;selectedList2.appendChild(availableList2.options.item(a))}selectNone(selectedList2,availableList2);setSize(selectedList2,availableList2)}function delAll2(){for(i=selectedList2.length-1;0<=i;i--)availableList2.appendChild(selectedList2.item(i));selectNone(selectedList2,availableList2);setSize(selectedList2,availableList2)}
function addAll2(){for(i=availableList2.length-1;0<=i;i--)selectedList2.appendChild(availableList2.item(i));selectNone(selectedList2,availableList2);setSize(selectedList2,availableList2)}
function checkCboValue(a){if(-1!=a.selectedIndex){var b=a.options[a.selectedIndex].text;a=b.substring(b.length-10,b.length);b=b.substring(b.length-5,b.length);"<not used>"==a&&GetAlertTextPopUp("This selected value not used in list!");"<KSD>"==b&&GetAlertTextPopUp("M\u1ee5c ch\u1ecdn kh\u00f4ng \u0111\u01b0\u1ee3c s\u1eed d\u1ee5ng trong danh s\u00e1ch!")}}
function OnMouseOver(a,b){try{var d=$find(a).get_selectedItem().get_value(),c=$find(a).findItemByValue(d);void 0!=c.get_attributes().getAttribute("Color1")&&""!=c.get_attributes().getAttribute("Color1")&&(b.title=c.get_attributes().getAttribute("Color1"))}catch(e){}}
function checkRadCboValue(a){if(-1!=a.selectedIndex){var b=a.value;a=b.substring(b.length-10,b.length);b=b.substring(b.length-5,b.length);"<not used>"==a&&GetAlertTextPopUp("This selected value not used in list!");"<KSD>"==b&&GetAlertTextPopUp("M\u1ee5c ch\u1ecdn kh\u00f4ng \u0111\u01b0\u1ee3c s\u1eed d\u1ee5ng trong danh s\u00e1ch!")}}function checkEvent(a){a||(a=window.event);a.target?targ=a.target:a.srcElement&&(targ=a.srcElement);showHideToolTip(targ,a,a.type)}
function showHideToolTip(a,b,d){var c={},c=document.getElementById("tooltip");c.innerHTML=a.options[a.selectedIndex].value;"mouseout"==d?c.style.display="none":(c.style.display="inline",c.style.top=b.y+15,c.style.left=b.x+10)}
function keySort(a,b){void 0==a.keypressBuffer&&(a.keypressBuffer="");var d=String.fromCharCode(window.event.keyCode);a.keypressBuffer+=d;b||(a.keypressBuffer=a.keypressBuffer.toLowerCase());for(var c=a.options.length,e=0;e<c;e++){var f=a.options[e].text;b||(f=f.toLowerCase());if(0==f.indexOf(a.keypressBuffer,0))return a.selectedIndex=e,!1}a.keypressBuffer=d;return!0}
function getChuKyLuong(a,b,d,c){var e=document.getElementById(a).value;if(""==e)document.getElementById(d).value="",document.getElementById(c).value="";else{b=document.getElementById(b).value;a=parseInt(e)-1;var f=b;"0"==a&&(a=12,f=parseInt(b)-1);10>a&&(a="0"+a);10>e&&(e="0"+e);document.getElementById(d).value="27/"+a+"/"+f;document.getElementById(c).value="26/"+e+"/"+b}}function TableAutoCheck(a,b){""!=a.value&&(a.parentNode.parentNode.cells[b].childNodes[0].checked=!0)}
function TableIsCheck(a,b,d){a=document.getElementById(a);for(var c=1;c<a.rows.length;c++)if(!0==a.rows[c].cells[b].childNodes[0].checked)return!0;!0==d&&alert("Vui l\u00f2ng ch\u1ecdn \u00edt nh\u1ea5t 1 m\u1eabu tin!");return!1}function TableCheckAll(a){for(var b=a.parentNode.parentNode.parentNode,d=0,c=0;c<b.rows[0].cells.length;c++)"none"==b.rows[0].cells[c].style.display&&(d+=1);for(c=1;c<b.rows.length;c++)b.rows[c].cells[a.parentNode.cellIndex+d].childNodes[0].checked=a.checked}
function GridCheckAll(a,b,d){var c=GetControl(a),e=c.rows.length,f=2;1<c.rows[e-1].cells[0].colSpan?e-=1:f-=1;b=GetControl(a+"__ctl"+f+"_"+b);for(c=1;c<e;c++){var g=GetControl(a+"__ctl"+(c+f)+"_"+d);!1==g.disabled&&(g.checked=b.checked)}}function GridIsCheck(a,b,d){var c=GetControl(a),e=c.rows.length,f=2;1<c.rows[e-1].cells[0].colSpan?e-=1:f-=1;for(c=1;c<e;c++)if(GetControl(a+"__ctl"+(c+f)+"_"+b).checked)return!0;!0==d&&alert("Vui l\u00f2ng ch\u1ecdn \u00edt nh\u1ea5t 1 m\u1eabu tin!");return!1}
function GridIsNotNullAllControl(a,b,d,c){var e=GetControl(a),f=e.rows.length,g=2;1<e.rows[f-1].cells[0].colSpan?f-=1:g-=1;for(e=1;e<f;e++)if(GetControl(a+"__ctl"+(e+g)+"_"+b).checked){var h=GetControl(a+"__ctl"+(e+g)+"_"+d);if("text"==h.type.toLowerCase()&&""==h.value)return null!=c&&alert("Vui l\u00f2ng nh\u1eadp "+c),h.focus(),!1;if(null!=h.type.toLowerCase().match("select")&&""==h.options[h.selectedIndex].value)return null!=c&&alert("Vui l\u00f2ng ch\u1ecdn "+c),h.focus(),!1}return!0}
function IsNotNullControl(a,b){var d=document.getElementById("_ctl0_"+a);return"text"==d.type.toLowerCase()&&""==d.value?(null!=b&&alert("Vui l\u00f2ng nh\u1eadp "+b),d.focus(),!1):null!=d.type.toLowerCase().match("select")&&""==d.options[d.selectedIndex].value?(null!=b&&alert("Vui l\u00f2ng ch\u1ecdn "+b),d.focus(),!1):!0}
function SetDateVN(a,b,d){try{if(!(1<=a&&31>=a))throw"Ngay";if(!(1<=b&&12>=b))throw"Thang";if(1>d)throw"Nam";var c=new Date;c.setFullYear(d,b-1,a);return c}catch(e){return"Ngay"==e?alert("L\u1ed7i vi ph\u1ea1m Ng\u00e0y"):"Thang"==e?alert("L\u1ed7i vi ph\u1ea1m Th\u00e1ng"):"Nam"==e?alert("L\u1ed7i vi ph\u1ea1m N\u0103m"):alert(e.discription),null}}
function ConvertDateVN(a,b){var d=a.getDate(),d=10>d?"0"+d:d,c=a.getMonth()+1,c=10>c?"0"+c:c,e=a.getFullYear();return null!=b?d+b+c+b+e:d+"/"+c+"/"+e}function NgayNhoHon(a,b){var d=parseInt(a.substring(0,2),10),c=parseInt(a.substring(3,5),10),e=parseInt(a.substring(6,10),10),f=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return e<h?!0:e>h?!1:c<g?!0:c>g?!1:d<f?!0:!1}
function NgayNhoHonBang(a,b){var d=parseInt(a.substring(0,2),10),c=parseInt(a.substring(3,5),10),e=parseInt(a.substring(6,10),10),f=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return e<h?!0:e>h?!1:c<g?!0:c>g?!1:d<=f?!0:!1}
function NgayLonHon(a,b){var d=parseInt(a.substring(0,2),10),c=parseInt(a.substring(3,5),10),e=parseInt(a.substring(6,10),10),f=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return e>h?!0:e<h?!1:c>g?!0:c<g?!1:d>f?!0:!1}
function NgayLonHonBang(a,b){var d=parseInt(a.substring(0,2),10),c=parseInt(a.substring(3,5),10),e=parseInt(a.substring(6,10),10),f=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return e>h?!0:e<h?!1:c>g?!0:c<g?!1:d>=f?!0:!1}function NgayNamTrongDoan(a,b,d){return NgayLonHon(b,d)||NgayNhoHon(a,b)||NgayLonHon(a,d)?!1:!0}function GetControl(a){return document.getElementById("_ctl0_"+a)}
function GetValueControl(a){a=document.getElementById("_ctl0_"+a);if("text"==a.type.toLowerCase())return a.value;if(null!=a.type.toLowerCase().match("select"))return a.options[a.selectedIndex].value}
function CheckDecimal(a,b){for(var d=a.value.length,c=0;c<d;c++)0==a.value.indexOf("0")&&(a.value=a.value.substring(1,a.value.length));if(""!=a.value)if(-1==a.value.indexOf(".")){a.value+=".";for(c=0;c<b;c++)a.value+="0"}else{for(c=d=0;c<a.value.length;c++)"."==a.value[c]&&d++;if(2<=d)alert("Gi\u00e1 tr\u1ecb kh\u00f4ng h\u1ee3p l\u1ec7"),a.value="";else{0==a.value.indexOf(".")&&(a.value="0"+a.value);if(a.value.indexOf(".")==a.value.length-1)for(c=0;c<b;c++)a.value+="0";c=parseFloat(a.value,10).toFixed(b);
a.value=c}}}function OpenPopUpEmpSearch(a,b){CurWindow=window.open("FormPage.aspx?Ascx=Common/Form/EmpSearchPopup.ascx&Return="+b+"&txtName="+a.id,"SearchEmp","toolbar=0,status=no,menubar=no,scrollbars=1,resizable=yes,copyhistory=yes,width=650,height=700,align=top");CurWindow.focus()}function LTrim(a){return a.replace(/\s*((\S+\s*)*)/,"$1")}function RTrim(a){return a.replace(/((\s*\S+)*)\s*/,"$1")}function TrimLR(a){return LTrim(RTrim(a))}
function CheckIsNull(a,b){if(null==document.getElementById("_ctl0_"+a))return!0;if(""==TrimLR(document.getElementById("_ctl0_"+a).value))return GetAlertError(iTotal,DSAlert,b),document.getElementById("_ctl0_"+a).value="",document.getElementById("_ctl0_"+a).focus(),!1}function checkIsNullReturn00(a){""==a.value&&(a.value="00")}function CheckIsNull_RCB(a,b){var d=$find("_ctl0_"+a);return""==d.get_value()?(GetAlertError(iTotal,DSAlert,b),d.get_inputDomElement().focus(),!1):!0}
function CheckIsNull_RCBGrid(a,b){var d=$find(a);return""==d.get_value()?(GetAlertError(iTotal,DSAlert,b),d.get_inputDomElement().focus(),!1):!0}function SearchListUser(a,b){for(var d=document.getElementById(b),c=d.length,e="",f=a.value.toUpperCase(),g=0;g<c;g++)if(e=d.item(g).text.toUpperCase(),"-1"!=e.indexOf(f)){document.getElementById(b).selectedIndex=g;break}return!1}
function SearchLeft(a,b){for(var d=document.getElementById(b),c="",e=document.getElementById(a).value.toUpperCase(),c=document.getElementById(b).selectedIndex,f=c-1;0<=f;f--)if(c=d.item(f).text.toUpperCase(),c=c.indexOf(e),"-1"!=c){document.getElementById(b).selectedIndex=f;break}return!1}
function SearchRight(a,b){for(var d=document.getElementById(b),c=d.length,e="",f=document.getElementById(a).value.toUpperCase(),e=document.getElementById(b).selectedIndex,g=e+1;g<c;g++)if(e=d.item(g).text.toUpperCase(),e=e.indexOf(f),"-1"!=e){document.getElementById(b).selectedIndex=g;break}return!1}function NoneCheckValid(){return!0}
function DisableAllButton(a){var b=Array(99);b[0]="_ctl0_btnSearch";b[1]="_ctl0_btnView";b[2]="_ctl0_btnAddNew";b[3]="_ctl0_btnDetail";b[4]="_ctl0_btnList";b[5]="_ctl0_btnBack";b[6]="_ctl0_btnSelect";b[7]="_ctl0_btnChoose";b[8]="_ctl0_btnClose";b[9]="_ctl0_btnHistory";b[10]="_ctl0_btnAdd";b[11]="_ctl0_btnCreate";b[12]="_ctl0_btnCalc";b[13]="_ctl0_btnSave";b[14]="_ctl0_btnChange";b[15]="_ctl0_btnUpdate";b[16]="_ctl0_btnCancel";b[17]="_ctl0_btnFill";b[18]="_ctl0_btnCopy";b[19]="_ctl0_btnEdit";b[20]=
"_ctl0_btnDel";b[21]="_ctl0_btnRemove";b[22]="_ctl0_btnDelete";b[23]="_ctl0_btnApproved";b[24]="_ctl0_btnReject";b[25]="_ctl0_btnExport";b[26]="_ctl0_btnImport";b[27]="_ctl0_btnSubmit";b[28]="_ctl0_btnTransfer";b[29]="_ctl0_btnLock";b[30]="_ctl0_btnUnLock";b[31]="_ctl0_btnExtend";b[31]="_ctl0_btnReset";b[32]="_ctl0_btnProcess";b[33]="_ctl0_btnAdd1";b[34]="_ctl0_btnAdd2";b[35]="_ctl0_btnExportAll";b[36]="_ctl0_btnSave2";b[37]="_ctl0_btnReCalc";b[38]="_ctl0_btnFill2";b[39]="_ctl0_btnFill_GioBatDauTT";
b[40]="_ctl0_btnFill_GioKetThucTT";b[41]="_ctl0_btnFill_DienGiai";b[42]="_ctl0_btnFill_";b[43]="_ctl0_btnFill__";b[44]="_ctl0_btnFill___";b[45]="_ctl0_btnFill_QuaNgaySauTT";b[46]="_ctl0_btnFill1";b[47]="_ctl0_btnFill3";b[48]="_ctl0_btnFill4";b[49]="_ctl0_btnFill5";b[50]="_ctl0_btnFill6";b[51]="_ctl0_btnFill7";b[52]="_ctl0_btnFill8";b[53]="_ctl0_btnFill9";b[54]="_ctl0_btnFill10";b[55]="_ctl0_btnFill11";b[56]="_ctl0_btnFill12";b[57]="_ctl0_btnFill13";b[58]="_ctl0_btnFill14";b[59]="_ctl0_btnFill15";
b[60]="_ctl0_btnFill16";b[61]="_ctl0_btnFill17";b[62]="_ctl0_btnFill18";b[63]="_ctl0_btnFill19";b[64]="_ctl0_btnFill20";b[65]="_ctl0_btnFill21";b[66]="_ctl0_btnFill22";b[67]="_ctl0_btnFill23";b[68]="_ctl0_btnFill24";b[69]="_ctl0_btnSaveEx";b[70]="_ctl0_btnDeleteEx";b[71]="_ctl0_btnTransferEx";b[72]="_ctl0_btnRejectEx";b[73]="_ctl0_btnFill_TangCa";b[74]="_ctl0_btnFill_GioNgayDK";b[75]="_ctl0_btnFill_GioDemDK";b[76]="_ctl0_btnFill_GioNghiBuDK";b[77]="_ctl0_btnFill_GhiChu";b[78]="_ctl0_btnFill_TuGio_TheoCa";
b[79]="_ctl0_btnFill_DenGio_TheoCa";b[80]="_ctl0_btnCloseAll";b[81]="_ctl0_btnExport_";b[82]="_ctl0_btnApprove";b[83]="_ctl0_btnImport_";b[84]="_ctl0_btnFill_GioNghiBuDemDK";b[85]="_ctl0_btnSearchOT";b[86]="_ctl0_btnAddNewOT";b[87]="_ctl0_btnDeleteOT";b[88]="_ctl0_btnSearchP";b[89]="_ctl0_btnAddNewP";b[90]="_ctl0_btnDeleteP";b[91]="_ctl0_btnSearchPTG";b[92]="_ctl0_btnAddNewPTG";b[93]="_ctl0_btnDeletePTG";b[94]="_ctl0_btnSearchOff";b[95]="_ctl0_btnAddNewOff";b[96]="_ctl0_btnDeleteOff";b[97]="_ctl0_btnSearchAll";
b[98]="_ctl0_btnAddNewAll";b[99]="_ctl0_btnDeleteAll";for(i=0;i<b.length;i++)null!=document.getElementById(b[i])&&(document.getElementById(b[i]).className="disable",document.getElementById(b[i]).disabled=!0,document.getElementById(b[i]).onclick=ignoreClick);__doPostBack(a,"")}function groupExpanded(){$telerik.isIE7&&$telerik.$("tr.rgGroupHeader:visible").removeClass("adjustedGroupHeader")}
function groupCollapsed(){$telerik.isIE7&&$telerik.$("tr.rgGroupHeader:hidden").addClass("adjustedGroupHeader")}function CheckAllCheckBoxList(a,b){for(var d=document.getElementById(a),c=0;c<d.getElementsByTagName("input").length;c++)document.getElementById(d.id+"_"+c).checked=b.checked;return!1}function GetSelectedValueRadiobuttonList(a){a=document.getElementById(a).getElementsByTagName("input");for(x=0;x<a.length;++x)if("radio"==a[x].type&&a[x].checked)return a[x].value}
function chkComboShowSelectedItem(a){var b=$find("_ctl0_"+a);if(null!=b){for(var d=b.get_items(),c="",e="",f=0;f<d.get_count();f++){var g=d.getItem(f),h=GetControlByType("checkbox",a+"_i"+f.toString());null!=h&&0<h.length&&h[0].checked&&(""!=c&&(c+="; "),c+=g.get_text(),""!=e&&(e+=";"),e+=g.get_value())}b.trackChanges();b.set_text(c);b.set_value(e);b.get_element().title=c;b.commitChanges()}}
function chkComboSelectAllCombo(a,b){var d=GetControlByType("checkbox",b);if(null!=d){for(var c=0;c<d.length;c++)d[c].checked=a.checked;chkComboShowSelectedItem(b)}}function CheckIsNull_chkCombo(a,b){var d=GetControlByType("checkbox",a),c=$find("_ctl0_"+a);if(null==d)return null!=c&&(GetAlertError(iTotal,DSAlert,b),d=c.get_inputDomElement(),d.focus()),!1;for(var e=0;e<d.length;e++)if(d[e].checked)return!0;null!=c&&(GetAlertError(iTotal,DSAlert,b),d=c.get_inputDomElement(),d.focus());return!1}
function CheckIsOne_chkCombo(a,b){var d=GetControlByType("checkbox",a+"_i"),c=$find("_ctl0_"+a);if(null==d)return null!=c&&(GetAlertError(iTotal,DSAlert,b),d=c.get_inputDomElement(),d.focus()),!0;for(var e=0,f=0;f<d.length;f++)d[f].checked&&e++;if(0==e||1==e)return!0;null!=c&&(GetAlertError(iTotal,DSAlert,b),d=c.get_inputDomElement(),d.focus());return!1}
function GetControlByType(a,b){for(var d,c=[],e=0;e<document.forms[0].elements.length;e++)d=document.forms[0].elements[e],d.type==a&&0<=d.id.indexOf(b)&&(c[c.length]=d);return c}function CreateDate(a,b,d){1==b?(b=12,d-=1):b-=1;return new Date(d,b,a)}
function GetDays(a,b){var d=a.split("/"),c=b.split("/");if(!(null==d||2>d.length)){var e=eval(d[2]),f=eval(d[1]),g=eval(d[0]);if(!(null==c||2>c.length)){var d=eval(c[2]),h=eval(c[1]),c=eval(c[0]),e=CreateDate(g,f,e),f=CreateDate(c,h,d);return Math.floor((f-e)/86400/1E3)}}}
function EnableLinkButton(a){if(-1==navigator.userAgent.toLowerCase().indexOf("msie")){a=$("a[id$="+a+"]");a.attr("disabled");a.removeAttr("disabled");var b=a.attr("myCustomAttr");if(void 0==b){for(b=a.attr("id");0<=b.indexOf("_");)b=b.replace("_","$");0==b.indexOf("$")&&(b="_"+b.substring(1,b.length));b="javascript:__doPostBack('"+b+"', '')"}a.attr("href",b).removeClass("disable");b=a.attr("myCustomAttr_click");void 0!=b&&a.attr("onclick",b)}else document.getElementById("_ctl0_"+a).removeAttribute("className",
"disable"),document.getElementById("_ctl0_"+a).disabled=!1}
function DisableLinkButton(a){if(-1==navigator.userAgent.toLowerCase().indexOf("msie")){a=$("a[id$="+a+"]");var b;if("disabled"==a.attr("disabled")){for(b=a.attr("id");0<=b.indexOf("_");)b=b.replace("_","$");0==b.indexOf("$")&&(b="_"+b.substring(1,b.length));b="javascript:__doPostBack('"+b+"', '')";a.attr("myCustomAttr",b)}else b=a.attr("href");try{a.removeAttr("href").attr("myCustomAttr",b).addClass("disable")}catch(d){}RemoveOnClickLinkButtonDisabled()}else document.getElementById("_ctl0_"+a).setAttribute("className",
"disable"),document.getElementById("_ctl0_"+a).disabled=!0}
function DisableLinkButton_PostBack(a){if(-1==navigator.userAgent.toLowerCase().indexOf("msie")){a=$("a[id$="+a+"]");var b;if("disabled"==a.attr("disabled")){for(b=a.attr("id");0<=b.indexOf("_");)b=b.replace("_","$");0==b.indexOf("$")&&(b="_"+b.substring(1,b.length));b="javascript:__doPostBack('"+b+"', '')";a.attr("myCustomAttr",b)}else b=a.attr("href");a.removeAttr("href").attr("myCustomAttr",b).addClass("disable")}else document.getElementById("_ctl0_"+a).setAttribute("className","disable"),document.getElementById("_ctl0_"+
a).disabled=!0}function ignoreClick(){return!1}function GiaiChuanHoaKiTuDacBietJS(a){return a=a.replace("&#39;","'")}
function FillData_RadGrid(a,b,d,c,e,f){try{if(!1==GridCheck_RadGrid("_ctl0_"+a,"chkSelect"))return GetAlertError(iTotal,DSAlert,"0001"),!1;var g="";"TextBox"==b?g=document.getElementById("_ctl0_"+d):"RadComBoBox"==b?g=$find("_ctl0_"+e):"CheckBox"==b&&(g=document.getElementById("_ctl0_"+d));var h=$find("_ctl0_"+a).get_masterTableView();if(null!=h){var j=h.get_dataItems().length;if(0<j)for(i=0;i<j;i++){var k=h.get_dataItems()[i],m=k.findElement("chkSelect");if(!1==m.disabled&&!0==m.checked)if("TextBox"==
c)k.findElement(e).value=g.value;else if("DropDownList"==c){var n=k.findElement(e);!1==n.disabled&&(n.options[n.selectedIndex].text=g.get_text(),n.options[n.selectedIndex].value=g.get_value())}else"CheckBox"==c&&(k.findElement(e).checked=g.checked)}}}catch(p){""!=f&&GetAlertError(iTotal,DSAlert,f)}return!1}
function FillData_RadGrid_GioPhut(a,b,d,c,e,f){try{if(!1==GridCheck_RadGrid("_ctl0_"+a,"chkSelect"))return GetAlertError(iTotal,DSAlert,"0001"),!1;var g=0,h=0,g=document.getElementById("_ctl0_"+b).value,h=document.getElementById("_ctl0_"+d).value,j=$find("_ctl0_"+a).get_masterTableView();if(null!=j){var k=j.get_dataItems().length;if(0<k)for(i=0;i<k;i++){var m=j.get_dataItems()[i],n=m.findElement("chkSelect");!1==n.disabled&&!0==n.checked&&(m.findElement(c).value=CheckFloat(g),m.findElement(e).value=
CheckFloat(h),LEN_HOUR(m.findElement(c)),LEN_HOUR(m.findElement(e)))}}}catch(p){""!=f&&GetAlertError(iTotal,DSAlert,f)}return!1};