#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikWebApp1.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iHRP_V32")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHR_tblEmp(HR_tblEmp instance);
    partial void UpdateHR_tblEmp(HR_tblEmp instance);
    partial void DeleteHR_tblEmp(HR_tblEmp instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iHRP_V32ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HR_tblEmp> HR_tblEmps
		{
			get
			{
				return this.GetTable<HR_tblEmp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HR_tblEmp")]
	public partial class HR_tblEmp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmpID;
		
		private string _EmpCode;
		
		private string _EmpCodeOld;
		
		private string _KeyNum;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<System.DateTime> _ProbationFrom;
		
		private System.Nullable<System.DateTime> _ProbationEnd;
		
		private System.Nullable<int> _LSStatusChangeID;
		
		private System.Nullable<int> _LSCompanyID;
		
		private System.Nullable<int> _LSLevel1ID;
		
		private System.Nullable<int> _LSLevel2ID;
		
		private System.Nullable<int> _LSLevel3ID;
		
		private string _LSPositionID;
		
		private System.Nullable<int> _LSJobTitleID;
		
		private System.Nullable<int> _LSLocationID;
		
		private string _LSJobClassID;
		
		private string _LSGradeID;
		
		private string _LSRankID;
		
		private string _LSJobCodeID;
		
		private string _LSEmpTypeID;
		
		private string _LSWorkTypeID;
		
		private System.Nullable<int> _EmpID_ReportTo;
		
		private bool _Active;
		
		private string _EmailComp;
		
		private string _TelephoneComp;
		
		private string _Creater;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private string _Editer;
		
		private System.Nullable<System.DateTime> _EditTime;
		
		private string _LSRESourceID;
		
		private System.Nullable<decimal> _BasicSalary;
		
		private string _LineManager;
		
		private string _DottedManager;
		
		private string _PlanID;
		
		private string _LSJobTitleID_Recuit;
		
		private string _CandidateID;
		
		private System.Nullable<System.DateTime> _StartDateOld;
		
		private string _LSMUPCID;
		
		private string _LSEmpGroupID;
		
		private string _LSEmpSubGroupID;
		
		private string _LSJobFunctionID;
		
		private string _LSActionDescriptionID;
		
		private System.Nullable<int> _LSCurrencyTypeID;
		
		private System.Nullable<bool> _IsNET;
		
		private string _LSTerritoryID;
		
		private string _ExtentionPhone;
		
		private System.Nullable<bool> _Active_temp;
		
		private System.Nullable<int> _SupervisorID;
		
		private string _Signer1ID;
		
		private string _Signer2ID;
		
		private string _OtherRelationship;
		
		private string _PrimaryTask;
		
		private string _PluralityTask;
		
		private string _ReplacementTask;
		
		private string _OtherTask;
		
		private System.Nullable<bool> _isOfficial;
		
		private string _LSJobTitleID_KN;
		
		private string _ContractID_Cur;
		
		private string _ContractNo_Cur;
		
		private string _contractCode_Cur;
		
		private System.Nullable<System.DateTime> _ContractEffectiveDate_Cur;
		
		private System.Nullable<System.DateTime> _ContractToDate_Cur;
		
		private System.Nullable<decimal> _ContractSalary_Cur;
		
		private System.Nullable<int> _Duration_Cur;
		
		private string _LSJobTitleID_KN2;
		
		private string _ContractTypeID_Cur;
		
		private System.Nullable<System.DateTime> _NgayNghiViec;
		
		private System.Nullable<int> _LSLoaiHinhNhanVienID;
		
		private System.Nullable<int> _LSLoaiNhanVienID;
		
		private System.Nullable<int> _LSNhomNhanVienID;
		
		private string _LSCapBacCongViecNoiBoID;
		
		private System.Nullable<int> _LSCapBacNhanVienID;
		
		private System.Nullable<int> _LSLoaiChiPhiID;
		
		private System.Nullable<int> _STT_Emp;
		
		private System.Nullable<bool> _NonEmp;
		
		private string _WorkingRecordID;
		
		private System.Nullable<int> _LSLoaiLaoDongID;
		
		private System.Nullable<int> _LSKhoiNhanVienID;
		
		private System.Nullable<int> _CopyFrom_EmpID;
		
		private string _ImportCreater;
		
		private System.Nullable<System.DateTime> _ImportCreateDate;
		
		private string _ImportEditer;
		
		private System.Nullable<System.DateTime> _ImportEditTime;
		
		private string _DanhMucQTLV1ID;
		
		private string _DanhMucQTLV2ID;
		
		private string _DanhMucQTLV3ID;
		
		private string _DanhMucQTLV4ID;
		
		private string _DanhMucQTLV5ID;
		
		private string _QTLVText1;
		
		private string _QTLVText2;
		
		private string _QTLVText3;
		
		private string _QTLVText4;
		
		private string _QTLVText5;
		
		private System.Nullable<bool> _QTLVBoolean1;
		
		private System.Nullable<bool> _QTLVBoolean2;
		
		private System.Nullable<System.DateTime> _QTLVDate1;
		
		private System.Nullable<System.DateTime> _QTLVDate2;
		
		private System.Nullable<int> _LSLevel4ID;
		
		private System.Nullable<int> _LSLevel5ID;
		
		private System.Nullable<int> _LSLevel6ID;
		
		private System.Nullable<int> _LSLevel7ID;
		
		private System.Nullable<int> _LSLevel8ID;
		
		private System.Nullable<int> _LSLevel9ID;
		
		private System.Nullable<int> _LSHLevel1ID;
		
		private System.Nullable<int> _LSHLevel2ID;
		
		private System.Nullable<int> _LSHLevel3ID;
		
		private System.Nullable<int> _LSHLevel4ID;
		
		private System.Nullable<int> _LSHLevel5ID;
		
		private System.Nullable<int> _LSHLevel6ID;
		
		private string _OldEmpCode;
		
		private System.Nullable<int> _RE_ProjectID;
		
		private System.Nullable<int> _RE_DemandID;
		
		private string _LSCostCenterID;
		
		private System.Nullable<int> _LSEESubGroupID;
		
		private string _CongViecDuocGiao;
		
		private string _SAPCode;
		
		private string _LSPhanLoaiNoiLamViecID;
		
		private System.Nullable<int> _EmpIDNhanVienChinh;
		
		private EntitySet<HR_tblEmp> _HR_tblEmps;
		
		private EntitySet<HR_tblEmp> _HR_tblEmps1;
		
		private EntityRef<HR_tblEmp> _HR_tblEmp1;
		
		private EntityRef<HR_tblEmp> _HR_tblEmp2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpIDChanging(int value);
    partial void OnEmpIDChanged();
    partial void OnEmpCodeChanging(string value);
    partial void OnEmpCodeChanged();
    partial void OnEmpCodeOldChanging(string value);
    partial void OnEmpCodeOldChanged();
    partial void OnKeyNumChanging(string value);
    partial void OnKeyNumChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnProbationFromChanging(System.Nullable<System.DateTime> value);
    partial void OnProbationFromChanged();
    partial void OnProbationEndChanging(System.Nullable<System.DateTime> value);
    partial void OnProbationEndChanged();
    partial void OnLSStatusChangeIDChanging(System.Nullable<int> value);
    partial void OnLSStatusChangeIDChanged();
    partial void OnLSCompanyIDChanging(System.Nullable<int> value);
    partial void OnLSCompanyIDChanged();
    partial void OnLSLevel1IDChanging(System.Nullable<int> value);
    partial void OnLSLevel1IDChanged();
    partial void OnLSLevel2IDChanging(System.Nullable<int> value);
    partial void OnLSLevel2IDChanged();
    partial void OnLSLevel3IDChanging(System.Nullable<int> value);
    partial void OnLSLevel3IDChanged();
    partial void OnLSPositionIDChanging(string value);
    partial void OnLSPositionIDChanged();
    partial void OnLSJobTitleIDChanging(System.Nullable<int> value);
    partial void OnLSJobTitleIDChanged();
    partial void OnLSLocationIDChanging(System.Nullable<int> value);
    partial void OnLSLocationIDChanged();
    partial void OnLSJobClassIDChanging(string value);
    partial void OnLSJobClassIDChanged();
    partial void OnLSGradeIDChanging(string value);
    partial void OnLSGradeIDChanged();
    partial void OnLSRankIDChanging(string value);
    partial void OnLSRankIDChanged();
    partial void OnLSJobCodeIDChanging(string value);
    partial void OnLSJobCodeIDChanged();
    partial void OnLSEmpTypeIDChanging(string value);
    partial void OnLSEmpTypeIDChanged();
    partial void OnLSWorkTypeIDChanging(string value);
    partial void OnLSWorkTypeIDChanged();
    partial void OnEmpID_ReportToChanging(System.Nullable<int> value);
    partial void OnEmpID_ReportToChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnEmailCompChanging(string value);
    partial void OnEmailCompChanged();
    partial void OnTelephoneCompChanging(string value);
    partial void OnTelephoneCompChanged();
    partial void OnCreaterChanging(string value);
    partial void OnCreaterChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnEditerChanging(string value);
    partial void OnEditerChanged();
    partial void OnEditTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEditTimeChanged();
    partial void OnLSRESourceIDChanging(string value);
    partial void OnLSRESourceIDChanged();
    partial void OnBasicSalaryChanging(System.Nullable<decimal> value);
    partial void OnBasicSalaryChanged();
    partial void OnLineManagerChanging(string value);
    partial void OnLineManagerChanged();
    partial void OnDottedManagerChanging(string value);
    partial void OnDottedManagerChanged();
    partial void OnPlanIDChanging(string value);
    partial void OnPlanIDChanged();
    partial void OnLSJobTitleID_RecuitChanging(string value);
    partial void OnLSJobTitleID_RecuitChanged();
    partial void OnCandidateIDChanging(string value);
    partial void OnCandidateIDChanged();
    partial void OnStartDateOldChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateOldChanged();
    partial void OnLSMUPCIDChanging(string value);
    partial void OnLSMUPCIDChanged();
    partial void OnLSEmpGroupIDChanging(string value);
    partial void OnLSEmpGroupIDChanged();
    partial void OnLSEmpSubGroupIDChanging(string value);
    partial void OnLSEmpSubGroupIDChanged();
    partial void OnLSJobFunctionIDChanging(string value);
    partial void OnLSJobFunctionIDChanged();
    partial void OnLSActionDescriptionIDChanging(string value);
    partial void OnLSActionDescriptionIDChanged();
    partial void OnLSCurrencyTypeIDChanging(System.Nullable<int> value);
    partial void OnLSCurrencyTypeIDChanged();
    partial void OnIsNETChanging(System.Nullable<bool> value);
    partial void OnIsNETChanged();
    partial void OnLSTerritoryIDChanging(string value);
    partial void OnLSTerritoryIDChanged();
    partial void OnExtentionPhoneChanging(string value);
    partial void OnExtentionPhoneChanged();
    partial void OnActive_tempChanging(System.Nullable<bool> value);
    partial void OnActive_tempChanged();
    partial void OnSupervisorIDChanging(System.Nullable<int> value);
    partial void OnSupervisorIDChanged();
    partial void OnSigner1IDChanging(string value);
    partial void OnSigner1IDChanged();
    partial void OnSigner2IDChanging(string value);
    partial void OnSigner2IDChanged();
    partial void OnOtherRelationshipChanging(string value);
    partial void OnOtherRelationshipChanged();
    partial void OnPrimaryTaskChanging(string value);
    partial void OnPrimaryTaskChanged();
    partial void OnPluralityTaskChanging(string value);
    partial void OnPluralityTaskChanged();
    partial void OnReplacementTaskChanging(string value);
    partial void OnReplacementTaskChanged();
    partial void OnOtherTaskChanging(string value);
    partial void OnOtherTaskChanged();
    partial void OnisOfficialChanging(System.Nullable<bool> value);
    partial void OnisOfficialChanged();
    partial void OnLSJobTitleID_KNChanging(string value);
    partial void OnLSJobTitleID_KNChanged();
    partial void OnContractID_CurChanging(string value);
    partial void OnContractID_CurChanged();
    partial void OnContractNo_CurChanging(string value);
    partial void OnContractNo_CurChanged();
    partial void OncontractCode_CurChanging(string value);
    partial void OncontractCode_CurChanged();
    partial void OnContractEffectiveDate_CurChanging(System.Nullable<System.DateTime> value);
    partial void OnContractEffectiveDate_CurChanged();
    partial void OnContractToDate_CurChanging(System.Nullable<System.DateTime> value);
    partial void OnContractToDate_CurChanged();
    partial void OnContractSalary_CurChanging(System.Nullable<decimal> value);
    partial void OnContractSalary_CurChanged();
    partial void OnDuration_CurChanging(System.Nullable<int> value);
    partial void OnDuration_CurChanged();
    partial void OnLSJobTitleID_KN2Changing(string value);
    partial void OnLSJobTitleID_KN2Changed();
    partial void OnContractTypeID_CurChanging(string value);
    partial void OnContractTypeID_CurChanged();
    partial void OnNgayNghiViecChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNghiViecChanged();
    partial void OnLSLoaiHinhNhanVienIDChanging(System.Nullable<int> value);
    partial void OnLSLoaiHinhNhanVienIDChanged();
    partial void OnLSLoaiNhanVienIDChanging(System.Nullable<int> value);
    partial void OnLSLoaiNhanVienIDChanged();
    partial void OnLSNhomNhanVienIDChanging(System.Nullable<int> value);
    partial void OnLSNhomNhanVienIDChanged();
    partial void OnLSCapBacCongViecNoiBoIDChanging(string value);
    partial void OnLSCapBacCongViecNoiBoIDChanged();
    partial void OnLSCapBacNhanVienIDChanging(System.Nullable<int> value);
    partial void OnLSCapBacNhanVienIDChanged();
    partial void OnLSLoaiChiPhiIDChanging(System.Nullable<int> value);
    partial void OnLSLoaiChiPhiIDChanged();
    partial void OnSTT_EmpChanging(System.Nullable<int> value);
    partial void OnSTT_EmpChanged();
    partial void OnNonEmpChanging(System.Nullable<bool> value);
    partial void OnNonEmpChanged();
    partial void OnWorkingRecordIDChanging(string value);
    partial void OnWorkingRecordIDChanged();
    partial void OnLSLoaiLaoDongIDChanging(System.Nullable<int> value);
    partial void OnLSLoaiLaoDongIDChanged();
    partial void OnLSKhoiNhanVienIDChanging(System.Nullable<int> value);
    partial void OnLSKhoiNhanVienIDChanged();
    partial void OnCopyFrom_EmpIDChanging(System.Nullable<int> value);
    partial void OnCopyFrom_EmpIDChanged();
    partial void OnImportCreaterChanging(string value);
    partial void OnImportCreaterChanged();
    partial void OnImportCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnImportCreateDateChanged();
    partial void OnImportEditerChanging(string value);
    partial void OnImportEditerChanged();
    partial void OnImportEditTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnImportEditTimeChanged();
    partial void OnDanhMucQTLV1IDChanging(string value);
    partial void OnDanhMucQTLV1IDChanged();
    partial void OnDanhMucQTLV2IDChanging(string value);
    partial void OnDanhMucQTLV2IDChanged();
    partial void OnDanhMucQTLV3IDChanging(string value);
    partial void OnDanhMucQTLV3IDChanged();
    partial void OnDanhMucQTLV4IDChanging(string value);
    partial void OnDanhMucQTLV4IDChanged();
    partial void OnDanhMucQTLV5IDChanging(string value);
    partial void OnDanhMucQTLV5IDChanged();
    partial void OnQTLVText1Changing(string value);
    partial void OnQTLVText1Changed();
    partial void OnQTLVText2Changing(string value);
    partial void OnQTLVText2Changed();
    partial void OnQTLVText3Changing(string value);
    partial void OnQTLVText3Changed();
    partial void OnQTLVText4Changing(string value);
    partial void OnQTLVText4Changed();
    partial void OnQTLVText5Changing(string value);
    partial void OnQTLVText5Changed();
    partial void OnQTLVBoolean1Changing(System.Nullable<bool> value);
    partial void OnQTLVBoolean1Changed();
    partial void OnQTLVBoolean2Changing(System.Nullable<bool> value);
    partial void OnQTLVBoolean2Changed();
    partial void OnQTLVDate1Changing(System.Nullable<System.DateTime> value);
    partial void OnQTLVDate1Changed();
    partial void OnQTLVDate2Changing(System.Nullable<System.DateTime> value);
    partial void OnQTLVDate2Changed();
    partial void OnLSLevel4IDChanging(System.Nullable<int> value);
    partial void OnLSLevel4IDChanged();
    partial void OnLSLevel5IDChanging(System.Nullable<int> value);
    partial void OnLSLevel5IDChanged();
    partial void OnLSLevel6IDChanging(System.Nullable<int> value);
    partial void OnLSLevel6IDChanged();
    partial void OnLSLevel7IDChanging(System.Nullable<int> value);
    partial void OnLSLevel7IDChanged();
    partial void OnLSLevel8IDChanging(System.Nullable<int> value);
    partial void OnLSLevel8IDChanged();
    partial void OnLSLevel9IDChanging(System.Nullable<int> value);
    partial void OnLSLevel9IDChanged();
    partial void OnLSHLevel1IDChanging(System.Nullable<int> value);
    partial void OnLSHLevel1IDChanged();
    partial void OnLSHLevel2IDChanging(System.Nullable<int> value);
    partial void OnLSHLevel2IDChanged();
    partial void OnLSHLevel3IDChanging(System.Nullable<int> value);
    partial void OnLSHLevel3IDChanged();
    partial void OnLSHLevel4IDChanging(System.Nullable<int> value);
    partial void OnLSHLevel4IDChanged();
    partial void OnLSHLevel5IDChanging(System.Nullable<int> value);
    partial void OnLSHLevel5IDChanged();
    partial void OnLSHLevel6IDChanging(System.Nullable<int> value);
    partial void OnLSHLevel6IDChanged();
    partial void OnOldEmpCodeChanging(string value);
    partial void OnOldEmpCodeChanged();
    partial void OnRE_ProjectIDChanging(System.Nullable<int> value);
    partial void OnRE_ProjectIDChanged();
    partial void OnRE_DemandIDChanging(System.Nullable<int> value);
    partial void OnRE_DemandIDChanged();
    partial void OnLSCostCenterIDChanging(string value);
    partial void OnLSCostCenterIDChanged();
    partial void OnLSEESubGroupIDChanging(System.Nullable<int> value);
    partial void OnLSEESubGroupIDChanged();
    partial void OnCongViecDuocGiaoChanging(string value);
    partial void OnCongViecDuocGiaoChanged();
    partial void OnSAPCodeChanging(string value);
    partial void OnSAPCodeChanged();
    partial void OnLSPhanLoaiNoiLamViecIDChanging(string value);
    partial void OnLSPhanLoaiNoiLamViecIDChanged();
    partial void OnEmpIDNhanVienChinhChanging(System.Nullable<int> value);
    partial void OnEmpIDNhanVienChinhChanged();
    #endregion
		
		public HR_tblEmp()
		{
			this._HR_tblEmps = new EntitySet<HR_tblEmp>(new Action<HR_tblEmp>(this.attach_HR_tblEmps), new Action<HR_tblEmp>(this.detach_HR_tblEmps));
			this._HR_tblEmps1 = new EntitySet<HR_tblEmp>(new Action<HR_tblEmp>(this.attach_HR_tblEmps1), new Action<HR_tblEmp>(this.detach_HR_tblEmps1));
			this._HR_tblEmp1 = default(EntityRef<HR_tblEmp>);
			this._HR_tblEmp2 = default(EntityRef<HR_tblEmp>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpCode", DbType="NVarChar(15)")]
		public string EmpCode
		{
			get
			{
				return this._EmpCode;
			}
			set
			{
				if ((this._EmpCode != value))
				{
					this.OnEmpCodeChanging(value);
					this.SendPropertyChanging();
					this._EmpCode = value;
					this.SendPropertyChanged("EmpCode");
					this.OnEmpCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpCodeOld", DbType="NVarChar(15)")]
		public string EmpCodeOld
		{
			get
			{
				return this._EmpCodeOld;
			}
			set
			{
				if ((this._EmpCodeOld != value))
				{
					this.OnEmpCodeOldChanging(value);
					this.SendPropertyChanging();
					this._EmpCodeOld = value;
					this.SendPropertyChanged("EmpCodeOld");
					this.OnEmpCodeOldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyNum", DbType="NVarChar(20)")]
		public string KeyNum
		{
			get
			{
				return this._KeyNum;
			}
			set
			{
				if ((this._KeyNum != value))
				{
					this.OnKeyNumChanging(value);
					this.SendPropertyChanging();
					this._KeyNum = value;
					this.SendPropertyChanged("KeyNum");
					this.OnKeyNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="Date")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProbationFrom", DbType="Date")]
		public System.Nullable<System.DateTime> ProbationFrom
		{
			get
			{
				return this._ProbationFrom;
			}
			set
			{
				if ((this._ProbationFrom != value))
				{
					this.OnProbationFromChanging(value);
					this.SendPropertyChanging();
					this._ProbationFrom = value;
					this.SendPropertyChanged("ProbationFrom");
					this.OnProbationFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProbationEnd", DbType="Date")]
		public System.Nullable<System.DateTime> ProbationEnd
		{
			get
			{
				return this._ProbationEnd;
			}
			set
			{
				if ((this._ProbationEnd != value))
				{
					this.OnProbationEndChanging(value);
					this.SendPropertyChanging();
					this._ProbationEnd = value;
					this.SendPropertyChanged("ProbationEnd");
					this.OnProbationEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSStatusChangeID", DbType="Int")]
		public System.Nullable<int> LSStatusChangeID
		{
			get
			{
				return this._LSStatusChangeID;
			}
			set
			{
				if ((this._LSStatusChangeID != value))
				{
					this.OnLSStatusChangeIDChanging(value);
					this.SendPropertyChanging();
					this._LSStatusChangeID = value;
					this.SendPropertyChanged("LSStatusChangeID");
					this.OnLSStatusChangeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSCompanyID", DbType="Int")]
		public System.Nullable<int> LSCompanyID
		{
			get
			{
				return this._LSCompanyID;
			}
			set
			{
				if ((this._LSCompanyID != value))
				{
					this.OnLSCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._LSCompanyID = value;
					this.SendPropertyChanged("LSCompanyID");
					this.OnLSCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel1ID", DbType="Int")]
		public System.Nullable<int> LSLevel1ID
		{
			get
			{
				return this._LSLevel1ID;
			}
			set
			{
				if ((this._LSLevel1ID != value))
				{
					this.OnLSLevel1IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel1ID = value;
					this.SendPropertyChanged("LSLevel1ID");
					this.OnLSLevel1IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel2ID", DbType="Int")]
		public System.Nullable<int> LSLevel2ID
		{
			get
			{
				return this._LSLevel2ID;
			}
			set
			{
				if ((this._LSLevel2ID != value))
				{
					this.OnLSLevel2IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel2ID = value;
					this.SendPropertyChanged("LSLevel2ID");
					this.OnLSLevel2IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel3ID", DbType="Int")]
		public System.Nullable<int> LSLevel3ID
		{
			get
			{
				return this._LSLevel3ID;
			}
			set
			{
				if ((this._LSLevel3ID != value))
				{
					this.OnLSLevel3IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel3ID = value;
					this.SendPropertyChanged("LSLevel3ID");
					this.OnLSLevel3IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSPositionID", DbType="NVarChar(12)")]
		public string LSPositionID
		{
			get
			{
				return this._LSPositionID;
			}
			set
			{
				if ((this._LSPositionID != value))
				{
					this.OnLSPositionIDChanging(value);
					this.SendPropertyChanging();
					this._LSPositionID = value;
					this.SendPropertyChanged("LSPositionID");
					this.OnLSPositionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSJobTitleID", DbType="Int")]
		public System.Nullable<int> LSJobTitleID
		{
			get
			{
				return this._LSJobTitleID;
			}
			set
			{
				if ((this._LSJobTitleID != value))
				{
					this.OnLSJobTitleIDChanging(value);
					this.SendPropertyChanging();
					this._LSJobTitleID = value;
					this.SendPropertyChanged("LSJobTitleID");
					this.OnLSJobTitleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLocationID", DbType="Int")]
		public System.Nullable<int> LSLocationID
		{
			get
			{
				return this._LSLocationID;
			}
			set
			{
				if ((this._LSLocationID != value))
				{
					this.OnLSLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LSLocationID = value;
					this.SendPropertyChanged("LSLocationID");
					this.OnLSLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSJobClassID", DbType="NVarChar(12)")]
		public string LSJobClassID
		{
			get
			{
				return this._LSJobClassID;
			}
			set
			{
				if ((this._LSJobClassID != value))
				{
					this.OnLSJobClassIDChanging(value);
					this.SendPropertyChanging();
					this._LSJobClassID = value;
					this.SendPropertyChanged("LSJobClassID");
					this.OnLSJobClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSGradeID", DbType="NVarChar(12)")]
		public string LSGradeID
		{
			get
			{
				return this._LSGradeID;
			}
			set
			{
				if ((this._LSGradeID != value))
				{
					this.OnLSGradeIDChanging(value);
					this.SendPropertyChanging();
					this._LSGradeID = value;
					this.SendPropertyChanged("LSGradeID");
					this.OnLSGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSRankID", DbType="NVarChar(12)")]
		public string LSRankID
		{
			get
			{
				return this._LSRankID;
			}
			set
			{
				if ((this._LSRankID != value))
				{
					this.OnLSRankIDChanging(value);
					this.SendPropertyChanging();
					this._LSRankID = value;
					this.SendPropertyChanged("LSRankID");
					this.OnLSRankIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSJobCodeID", DbType="NVarChar(12)")]
		public string LSJobCodeID
		{
			get
			{
				return this._LSJobCodeID;
			}
			set
			{
				if ((this._LSJobCodeID != value))
				{
					this.OnLSJobCodeIDChanging(value);
					this.SendPropertyChanging();
					this._LSJobCodeID = value;
					this.SendPropertyChanged("LSJobCodeID");
					this.OnLSJobCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEmpTypeID", DbType="NVarChar(12)")]
		public string LSEmpTypeID
		{
			get
			{
				return this._LSEmpTypeID;
			}
			set
			{
				if ((this._LSEmpTypeID != value))
				{
					this.OnLSEmpTypeIDChanging(value);
					this.SendPropertyChanging();
					this._LSEmpTypeID = value;
					this.SendPropertyChanged("LSEmpTypeID");
					this.OnLSEmpTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSWorkTypeID", DbType="NVarChar(12)")]
		public string LSWorkTypeID
		{
			get
			{
				return this._LSWorkTypeID;
			}
			set
			{
				if ((this._LSWorkTypeID != value))
				{
					this.OnLSWorkTypeIDChanging(value);
					this.SendPropertyChanging();
					this._LSWorkTypeID = value;
					this.SendPropertyChanged("LSWorkTypeID");
					this.OnLSWorkTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID_ReportTo", DbType="Int")]
		public System.Nullable<int> EmpID_ReportTo
		{
			get
			{
				return this._EmpID_ReportTo;
			}
			set
			{
				if ((this._EmpID_ReportTo != value))
				{
					if (this._HR_tblEmp2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpID_ReportToChanging(value);
					this.SendPropertyChanging();
					this._EmpID_ReportTo = value;
					this.SendPropertyChanged("EmpID_ReportTo");
					this.OnEmpID_ReportToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailComp", DbType="NVarChar(255)")]
		public string EmailComp
		{
			get
			{
				return this._EmailComp;
			}
			set
			{
				if ((this._EmailComp != value))
				{
					this.OnEmailCompChanging(value);
					this.SendPropertyChanging();
					this._EmailComp = value;
					this.SendPropertyChanged("EmailComp");
					this.OnEmailCompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelephoneComp", DbType="NVarChar(30)")]
		public string TelephoneComp
		{
			get
			{
				return this._TelephoneComp;
			}
			set
			{
				if ((this._TelephoneComp != value))
				{
					this.OnTelephoneCompChanging(value);
					this.SendPropertyChanging();
					this._TelephoneComp = value;
					this.SendPropertyChanged("TelephoneComp");
					this.OnTelephoneCompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creater", DbType="NVarChar(50)")]
		public string Creater
		{
			get
			{
				return this._Creater;
			}
			set
			{
				if ((this._Creater != value))
				{
					this.OnCreaterChanging(value);
					this.SendPropertyChanging();
					this._Creater = value;
					this.SendPropertyChanged("Creater");
					this.OnCreaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editer", DbType="NVarChar(50)")]
		public string Editer
		{
			get
			{
				return this._Editer;
			}
			set
			{
				if ((this._Editer != value))
				{
					this.OnEditerChanging(value);
					this.SendPropertyChanging();
					this._Editer = value;
					this.SendPropertyChanged("Editer");
					this.OnEditerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditTime
		{
			get
			{
				return this._EditTime;
			}
			set
			{
				if ((this._EditTime != value))
				{
					this.OnEditTimeChanging(value);
					this.SendPropertyChanging();
					this._EditTime = value;
					this.SendPropertyChanged("EditTime");
					this.OnEditTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSRESourceID", DbType="NVarChar(12)")]
		public string LSRESourceID
		{
			get
			{
				return this._LSRESourceID;
			}
			set
			{
				if ((this._LSRESourceID != value))
				{
					this.OnLSRESourceIDChanging(value);
					this.SendPropertyChanging();
					this._LSRESourceID = value;
					this.SendPropertyChanged("LSRESourceID");
					this.OnLSRESourceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSalary", DbType="Money")]
		public System.Nullable<decimal> BasicSalary
		{
			get
			{
				return this._BasicSalary;
			}
			set
			{
				if ((this._BasicSalary != value))
				{
					this.OnBasicSalaryChanging(value);
					this.SendPropertyChanging();
					this._BasicSalary = value;
					this.SendPropertyChanged("BasicSalary");
					this.OnBasicSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineManager", DbType="NVarChar(12)")]
		public string LineManager
		{
			get
			{
				return this._LineManager;
			}
			set
			{
				if ((this._LineManager != value))
				{
					this.OnLineManagerChanging(value);
					this.SendPropertyChanging();
					this._LineManager = value;
					this.SendPropertyChanged("LineManager");
					this.OnLineManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DottedManager", DbType="NVarChar(12)")]
		public string DottedManager
		{
			get
			{
				return this._DottedManager;
			}
			set
			{
				if ((this._DottedManager != value))
				{
					this.OnDottedManagerChanging(value);
					this.SendPropertyChanging();
					this._DottedManager = value;
					this.SendPropertyChanged("DottedManager");
					this.OnDottedManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanID", DbType="NVarChar(12)")]
		public string PlanID
		{
			get
			{
				return this._PlanID;
			}
			set
			{
				if ((this._PlanID != value))
				{
					this.OnPlanIDChanging(value);
					this.SendPropertyChanging();
					this._PlanID = value;
					this.SendPropertyChanged("PlanID");
					this.OnPlanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSJobTitleID_Recuit", DbType="NVarChar(12)")]
		public string LSJobTitleID_Recuit
		{
			get
			{
				return this._LSJobTitleID_Recuit;
			}
			set
			{
				if ((this._LSJobTitleID_Recuit != value))
				{
					this.OnLSJobTitleID_RecuitChanging(value);
					this.SendPropertyChanging();
					this._LSJobTitleID_Recuit = value;
					this.SendPropertyChanged("LSJobTitleID_Recuit");
					this.OnLSJobTitleID_RecuitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateID", DbType="NVarChar(12)")]
		public string CandidateID
		{
			get
			{
				return this._CandidateID;
			}
			set
			{
				if ((this._CandidateID != value))
				{
					this.OnCandidateIDChanging(value);
					this.SendPropertyChanging();
					this._CandidateID = value;
					this.SendPropertyChanged("CandidateID");
					this.OnCandidateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDateOld", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDateOld
		{
			get
			{
				return this._StartDateOld;
			}
			set
			{
				if ((this._StartDateOld != value))
				{
					this.OnStartDateOldChanging(value);
					this.SendPropertyChanging();
					this._StartDateOld = value;
					this.SendPropertyChanged("StartDateOld");
					this.OnStartDateOldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSMUPCID", DbType="NVarChar(12)")]
		public string LSMUPCID
		{
			get
			{
				return this._LSMUPCID;
			}
			set
			{
				if ((this._LSMUPCID != value))
				{
					this.OnLSMUPCIDChanging(value);
					this.SendPropertyChanging();
					this._LSMUPCID = value;
					this.SendPropertyChanged("LSMUPCID");
					this.OnLSMUPCIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEmpGroupID", DbType="NVarChar(12)")]
		public string LSEmpGroupID
		{
			get
			{
				return this._LSEmpGroupID;
			}
			set
			{
				if ((this._LSEmpGroupID != value))
				{
					this.OnLSEmpGroupIDChanging(value);
					this.SendPropertyChanging();
					this._LSEmpGroupID = value;
					this.SendPropertyChanged("LSEmpGroupID");
					this.OnLSEmpGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEmpSubGroupID", DbType="NVarChar(12)")]
		public string LSEmpSubGroupID
		{
			get
			{
				return this._LSEmpSubGroupID;
			}
			set
			{
				if ((this._LSEmpSubGroupID != value))
				{
					this.OnLSEmpSubGroupIDChanging(value);
					this.SendPropertyChanging();
					this._LSEmpSubGroupID = value;
					this.SendPropertyChanged("LSEmpSubGroupID");
					this.OnLSEmpSubGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSJobFunctionID", DbType="NVarChar(12)")]
		public string LSJobFunctionID
		{
			get
			{
				return this._LSJobFunctionID;
			}
			set
			{
				if ((this._LSJobFunctionID != value))
				{
					this.OnLSJobFunctionIDChanging(value);
					this.SendPropertyChanging();
					this._LSJobFunctionID = value;
					this.SendPropertyChanged("LSJobFunctionID");
					this.OnLSJobFunctionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSActionDescriptionID", DbType="NVarChar(12)")]
		public string LSActionDescriptionID
		{
			get
			{
				return this._LSActionDescriptionID;
			}
			set
			{
				if ((this._LSActionDescriptionID != value))
				{
					this.OnLSActionDescriptionIDChanging(value);
					this.SendPropertyChanging();
					this._LSActionDescriptionID = value;
					this.SendPropertyChanged("LSActionDescriptionID");
					this.OnLSActionDescriptionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSCurrencyTypeID", DbType="Int")]
		public System.Nullable<int> LSCurrencyTypeID
		{
			get
			{
				return this._LSCurrencyTypeID;
			}
			set
			{
				if ((this._LSCurrencyTypeID != value))
				{
					this.OnLSCurrencyTypeIDChanging(value);
					this.SendPropertyChanging();
					this._LSCurrencyTypeID = value;
					this.SendPropertyChanged("LSCurrencyTypeID");
					this.OnLSCurrencyTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNET", DbType="Bit")]
		public System.Nullable<bool> IsNET
		{
			get
			{
				return this._IsNET;
			}
			set
			{
				if ((this._IsNET != value))
				{
					this.OnIsNETChanging(value);
					this.SendPropertyChanging();
					this._IsNET = value;
					this.SendPropertyChanged("IsNET");
					this.OnIsNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSTerritoryID", DbType="NVarChar(12)")]
		public string LSTerritoryID
		{
			get
			{
				return this._LSTerritoryID;
			}
			set
			{
				if ((this._LSTerritoryID != value))
				{
					this.OnLSTerritoryIDChanging(value);
					this.SendPropertyChanging();
					this._LSTerritoryID = value;
					this.SendPropertyChanged("LSTerritoryID");
					this.OnLSTerritoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtentionPhone", DbType="NVarChar(10)")]
		public string ExtentionPhone
		{
			get
			{
				return this._ExtentionPhone;
			}
			set
			{
				if ((this._ExtentionPhone != value))
				{
					this.OnExtentionPhoneChanging(value);
					this.SendPropertyChanging();
					this._ExtentionPhone = value;
					this.SendPropertyChanged("ExtentionPhone");
					this.OnExtentionPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active_temp", DbType="Bit")]
		public System.Nullable<bool> Active_temp
		{
			get
			{
				return this._Active_temp;
			}
			set
			{
				if ((this._Active_temp != value))
				{
					this.OnActive_tempChanging(value);
					this.SendPropertyChanging();
					this._Active_temp = value;
					this.SendPropertyChanged("Active_temp");
					this.OnActive_tempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisorID", DbType="Int")]
		public System.Nullable<int> SupervisorID
		{
			get
			{
				return this._SupervisorID;
			}
			set
			{
				if ((this._SupervisorID != value))
				{
					this.OnSupervisorIDChanging(value);
					this.SendPropertyChanging();
					this._SupervisorID = value;
					this.SendPropertyChanged("SupervisorID");
					this.OnSupervisorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signer1ID", DbType="NVarChar(12)")]
		public string Signer1ID
		{
			get
			{
				return this._Signer1ID;
			}
			set
			{
				if ((this._Signer1ID != value))
				{
					this.OnSigner1IDChanging(value);
					this.SendPropertyChanging();
					this._Signer1ID = value;
					this.SendPropertyChanged("Signer1ID");
					this.OnSigner1IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signer2ID", DbType="NVarChar(12)")]
		public string Signer2ID
		{
			get
			{
				return this._Signer2ID;
			}
			set
			{
				if ((this._Signer2ID != value))
				{
					this.OnSigner2IDChanging(value);
					this.SendPropertyChanging();
					this._Signer2ID = value;
					this.SendPropertyChanged("Signer2ID");
					this.OnSigner2IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherRelationship", DbType="NVarChar(500)")]
		public string OtherRelationship
		{
			get
			{
				return this._OtherRelationship;
			}
			set
			{
				if ((this._OtherRelationship != value))
				{
					this.OnOtherRelationshipChanging(value);
					this.SendPropertyChanging();
					this._OtherRelationship = value;
					this.SendPropertyChanged("OtherRelationship");
					this.OnOtherRelationshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryTask", DbType="NVarChar(500)")]
		public string PrimaryTask
		{
			get
			{
				return this._PrimaryTask;
			}
			set
			{
				if ((this._PrimaryTask != value))
				{
					this.OnPrimaryTaskChanging(value);
					this.SendPropertyChanging();
					this._PrimaryTask = value;
					this.SendPropertyChanged("PrimaryTask");
					this.OnPrimaryTaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PluralityTask", DbType="NVarChar(500)")]
		public string PluralityTask
		{
			get
			{
				return this._PluralityTask;
			}
			set
			{
				if ((this._PluralityTask != value))
				{
					this.OnPluralityTaskChanging(value);
					this.SendPropertyChanging();
					this._PluralityTask = value;
					this.SendPropertyChanged("PluralityTask");
					this.OnPluralityTaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplacementTask", DbType="NVarChar(255)")]
		public string ReplacementTask
		{
			get
			{
				return this._ReplacementTask;
			}
			set
			{
				if ((this._ReplacementTask != value))
				{
					this.OnReplacementTaskChanging(value);
					this.SendPropertyChanging();
					this._ReplacementTask = value;
					this.SendPropertyChanged("ReplacementTask");
					this.OnReplacementTaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherTask", DbType="NVarChar(255)")]
		public string OtherTask
		{
			get
			{
				return this._OtherTask;
			}
			set
			{
				if ((this._OtherTask != value))
				{
					this.OnOtherTaskChanging(value);
					this.SendPropertyChanging();
					this._OtherTask = value;
					this.SendPropertyChanged("OtherTask");
					this.OnOtherTaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isOfficial", DbType="Bit")]
		public System.Nullable<bool> isOfficial
		{
			get
			{
				return this._isOfficial;
			}
			set
			{
				if ((this._isOfficial != value))
				{
					this.OnisOfficialChanging(value);
					this.SendPropertyChanging();
					this._isOfficial = value;
					this.SendPropertyChanged("isOfficial");
					this.OnisOfficialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSJobTitleID_KN", DbType="NVarChar(12)")]
		public string LSJobTitleID_KN
		{
			get
			{
				return this._LSJobTitleID_KN;
			}
			set
			{
				if ((this._LSJobTitleID_KN != value))
				{
					this.OnLSJobTitleID_KNChanging(value);
					this.SendPropertyChanging();
					this._LSJobTitleID_KN = value;
					this.SendPropertyChanged("LSJobTitleID_KN");
					this.OnLSJobTitleID_KNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractID_Cur", DbType="NVarChar(12)")]
		public string ContractID_Cur
		{
			get
			{
				return this._ContractID_Cur;
			}
			set
			{
				if ((this._ContractID_Cur != value))
				{
					this.OnContractID_CurChanging(value);
					this.SendPropertyChanging();
					this._ContractID_Cur = value;
					this.SendPropertyChanged("ContractID_Cur");
					this.OnContractID_CurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractNo_Cur", DbType="NVarChar(100)")]
		public string ContractNo_Cur
		{
			get
			{
				return this._ContractNo_Cur;
			}
			set
			{
				if ((this._ContractNo_Cur != value))
				{
					this.OnContractNo_CurChanging(value);
					this.SendPropertyChanging();
					this._ContractNo_Cur = value;
					this.SendPropertyChanged("ContractNo_Cur");
					this.OnContractNo_CurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contractCode_Cur", DbType="NVarChar(12)")]
		public string contractCode_Cur
		{
			get
			{
				return this._contractCode_Cur;
			}
			set
			{
				if ((this._contractCode_Cur != value))
				{
					this.OncontractCode_CurChanging(value);
					this.SendPropertyChanging();
					this._contractCode_Cur = value;
					this.SendPropertyChanged("contractCode_Cur");
					this.OncontractCode_CurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractEffectiveDate_Cur", DbType="Date")]
		public System.Nullable<System.DateTime> ContractEffectiveDate_Cur
		{
			get
			{
				return this._ContractEffectiveDate_Cur;
			}
			set
			{
				if ((this._ContractEffectiveDate_Cur != value))
				{
					this.OnContractEffectiveDate_CurChanging(value);
					this.SendPropertyChanging();
					this._ContractEffectiveDate_Cur = value;
					this.SendPropertyChanged("ContractEffectiveDate_Cur");
					this.OnContractEffectiveDate_CurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractToDate_Cur", DbType="Date")]
		public System.Nullable<System.DateTime> ContractToDate_Cur
		{
			get
			{
				return this._ContractToDate_Cur;
			}
			set
			{
				if ((this._ContractToDate_Cur != value))
				{
					this.OnContractToDate_CurChanging(value);
					this.SendPropertyChanging();
					this._ContractToDate_Cur = value;
					this.SendPropertyChanged("ContractToDate_Cur");
					this.OnContractToDate_CurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractSalary_Cur", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ContractSalary_Cur
		{
			get
			{
				return this._ContractSalary_Cur;
			}
			set
			{
				if ((this._ContractSalary_Cur != value))
				{
					this.OnContractSalary_CurChanging(value);
					this.SendPropertyChanging();
					this._ContractSalary_Cur = value;
					this.SendPropertyChanged("ContractSalary_Cur");
					this.OnContractSalary_CurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration_Cur", DbType="Int")]
		public System.Nullable<int> Duration_Cur
		{
			get
			{
				return this._Duration_Cur;
			}
			set
			{
				if ((this._Duration_Cur != value))
				{
					this.OnDuration_CurChanging(value);
					this.SendPropertyChanging();
					this._Duration_Cur = value;
					this.SendPropertyChanged("Duration_Cur");
					this.OnDuration_CurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSJobTitleID_KN2", DbType="NVarChar(12)")]
		public string LSJobTitleID_KN2
		{
			get
			{
				return this._LSJobTitleID_KN2;
			}
			set
			{
				if ((this._LSJobTitleID_KN2 != value))
				{
					this.OnLSJobTitleID_KN2Changing(value);
					this.SendPropertyChanging();
					this._LSJobTitleID_KN2 = value;
					this.SendPropertyChanged("LSJobTitleID_KN2");
					this.OnLSJobTitleID_KN2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractTypeID_Cur", DbType="NVarChar(150)")]
		public string ContractTypeID_Cur
		{
			get
			{
				return this._ContractTypeID_Cur;
			}
			set
			{
				if ((this._ContractTypeID_Cur != value))
				{
					this.OnContractTypeID_CurChanging(value);
					this.SendPropertyChanging();
					this._ContractTypeID_Cur = value;
					this.SendPropertyChanged("ContractTypeID_Cur");
					this.OnContractTypeID_CurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNghiViec", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNghiViec
		{
			get
			{
				return this._NgayNghiViec;
			}
			set
			{
				if ((this._NgayNghiViec != value))
				{
					this.OnNgayNghiViecChanging(value);
					this.SendPropertyChanging();
					this._NgayNghiViec = value;
					this.SendPropertyChanged("NgayNghiViec");
					this.OnNgayNghiViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLoaiHinhNhanVienID", DbType="Int")]
		public System.Nullable<int> LSLoaiHinhNhanVienID
		{
			get
			{
				return this._LSLoaiHinhNhanVienID;
			}
			set
			{
				if ((this._LSLoaiHinhNhanVienID != value))
				{
					this.OnLSLoaiHinhNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._LSLoaiHinhNhanVienID = value;
					this.SendPropertyChanged("LSLoaiHinhNhanVienID");
					this.OnLSLoaiHinhNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLoaiNhanVienID", DbType="Int")]
		public System.Nullable<int> LSLoaiNhanVienID
		{
			get
			{
				return this._LSLoaiNhanVienID;
			}
			set
			{
				if ((this._LSLoaiNhanVienID != value))
				{
					this.OnLSLoaiNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._LSLoaiNhanVienID = value;
					this.SendPropertyChanged("LSLoaiNhanVienID");
					this.OnLSLoaiNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSNhomNhanVienID", DbType="Int")]
		public System.Nullable<int> LSNhomNhanVienID
		{
			get
			{
				return this._LSNhomNhanVienID;
			}
			set
			{
				if ((this._LSNhomNhanVienID != value))
				{
					this.OnLSNhomNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._LSNhomNhanVienID = value;
					this.SendPropertyChanged("LSNhomNhanVienID");
					this.OnLSNhomNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSCapBacCongViecNoiBoID", DbType="NVarChar(12)")]
		public string LSCapBacCongViecNoiBoID
		{
			get
			{
				return this._LSCapBacCongViecNoiBoID;
			}
			set
			{
				if ((this._LSCapBacCongViecNoiBoID != value))
				{
					this.OnLSCapBacCongViecNoiBoIDChanging(value);
					this.SendPropertyChanging();
					this._LSCapBacCongViecNoiBoID = value;
					this.SendPropertyChanged("LSCapBacCongViecNoiBoID");
					this.OnLSCapBacCongViecNoiBoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSCapBacNhanVienID", DbType="Int")]
		public System.Nullable<int> LSCapBacNhanVienID
		{
			get
			{
				return this._LSCapBacNhanVienID;
			}
			set
			{
				if ((this._LSCapBacNhanVienID != value))
				{
					this.OnLSCapBacNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._LSCapBacNhanVienID = value;
					this.SendPropertyChanged("LSCapBacNhanVienID");
					this.OnLSCapBacNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLoaiChiPhiID", DbType="Int")]
		public System.Nullable<int> LSLoaiChiPhiID
		{
			get
			{
				return this._LSLoaiChiPhiID;
			}
			set
			{
				if ((this._LSLoaiChiPhiID != value))
				{
					this.OnLSLoaiChiPhiIDChanging(value);
					this.SendPropertyChanging();
					this._LSLoaiChiPhiID = value;
					this.SendPropertyChanged("LSLoaiChiPhiID");
					this.OnLSLoaiChiPhiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT_Emp", DbType="Int")]
		public System.Nullable<int> STT_Emp
		{
			get
			{
				return this._STT_Emp;
			}
			set
			{
				if ((this._STT_Emp != value))
				{
					this.OnSTT_EmpChanging(value);
					this.SendPropertyChanging();
					this._STT_Emp = value;
					this.SendPropertyChanged("STT_Emp");
					this.OnSTT_EmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NonEmp", DbType="Bit")]
		public System.Nullable<bool> NonEmp
		{
			get
			{
				return this._NonEmp;
			}
			set
			{
				if ((this._NonEmp != value))
				{
					this.OnNonEmpChanging(value);
					this.SendPropertyChanging();
					this._NonEmp = value;
					this.SendPropertyChanged("NonEmp");
					this.OnNonEmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkingRecordID", DbType="NVarChar(12)")]
		public string WorkingRecordID
		{
			get
			{
				return this._WorkingRecordID;
			}
			set
			{
				if ((this._WorkingRecordID != value))
				{
					this.OnWorkingRecordIDChanging(value);
					this.SendPropertyChanging();
					this._WorkingRecordID = value;
					this.SendPropertyChanged("WorkingRecordID");
					this.OnWorkingRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLoaiLaoDongID", DbType="Int")]
		public System.Nullable<int> LSLoaiLaoDongID
		{
			get
			{
				return this._LSLoaiLaoDongID;
			}
			set
			{
				if ((this._LSLoaiLaoDongID != value))
				{
					this.OnLSLoaiLaoDongIDChanging(value);
					this.SendPropertyChanging();
					this._LSLoaiLaoDongID = value;
					this.SendPropertyChanged("LSLoaiLaoDongID");
					this.OnLSLoaiLaoDongIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSKhoiNhanVienID", DbType="Int")]
		public System.Nullable<int> LSKhoiNhanVienID
		{
			get
			{
				return this._LSKhoiNhanVienID;
			}
			set
			{
				if ((this._LSKhoiNhanVienID != value))
				{
					this.OnLSKhoiNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._LSKhoiNhanVienID = value;
					this.SendPropertyChanged("LSKhoiNhanVienID");
					this.OnLSKhoiNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CopyFrom_EmpID", DbType="Int")]
		public System.Nullable<int> CopyFrom_EmpID
		{
			get
			{
				return this._CopyFrom_EmpID;
			}
			set
			{
				if ((this._CopyFrom_EmpID != value))
				{
					this.OnCopyFrom_EmpIDChanging(value);
					this.SendPropertyChanging();
					this._CopyFrom_EmpID = value;
					this.SendPropertyChanged("CopyFrom_EmpID");
					this.OnCopyFrom_EmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportCreater", DbType="NVarChar(50)")]
		public string ImportCreater
		{
			get
			{
				return this._ImportCreater;
			}
			set
			{
				if ((this._ImportCreater != value))
				{
					this.OnImportCreaterChanging(value);
					this.SendPropertyChanging();
					this._ImportCreater = value;
					this.SendPropertyChanged("ImportCreater");
					this.OnImportCreaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportCreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ImportCreateDate
		{
			get
			{
				return this._ImportCreateDate;
			}
			set
			{
				if ((this._ImportCreateDate != value))
				{
					this.OnImportCreateDateChanging(value);
					this.SendPropertyChanging();
					this._ImportCreateDate = value;
					this.SendPropertyChanged("ImportCreateDate");
					this.OnImportCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportEditer", DbType="NVarChar(50)")]
		public string ImportEditer
		{
			get
			{
				return this._ImportEditer;
			}
			set
			{
				if ((this._ImportEditer != value))
				{
					this.OnImportEditerChanging(value);
					this.SendPropertyChanging();
					this._ImportEditer = value;
					this.SendPropertyChanged("ImportEditer");
					this.OnImportEditerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportEditTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ImportEditTime
		{
			get
			{
				return this._ImportEditTime;
			}
			set
			{
				if ((this._ImportEditTime != value))
				{
					this.OnImportEditTimeChanging(value);
					this.SendPropertyChanging();
					this._ImportEditTime = value;
					this.SendPropertyChanged("ImportEditTime");
					this.OnImportEditTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhMucQTLV1ID", DbType="NVarChar(12)")]
		public string DanhMucQTLV1ID
		{
			get
			{
				return this._DanhMucQTLV1ID;
			}
			set
			{
				if ((this._DanhMucQTLV1ID != value))
				{
					this.OnDanhMucQTLV1IDChanging(value);
					this.SendPropertyChanging();
					this._DanhMucQTLV1ID = value;
					this.SendPropertyChanged("DanhMucQTLV1ID");
					this.OnDanhMucQTLV1IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhMucQTLV2ID", DbType="NVarChar(12)")]
		public string DanhMucQTLV2ID
		{
			get
			{
				return this._DanhMucQTLV2ID;
			}
			set
			{
				if ((this._DanhMucQTLV2ID != value))
				{
					this.OnDanhMucQTLV2IDChanging(value);
					this.SendPropertyChanging();
					this._DanhMucQTLV2ID = value;
					this.SendPropertyChanged("DanhMucQTLV2ID");
					this.OnDanhMucQTLV2IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhMucQTLV3ID", DbType="NVarChar(12)")]
		public string DanhMucQTLV3ID
		{
			get
			{
				return this._DanhMucQTLV3ID;
			}
			set
			{
				if ((this._DanhMucQTLV3ID != value))
				{
					this.OnDanhMucQTLV3IDChanging(value);
					this.SendPropertyChanging();
					this._DanhMucQTLV3ID = value;
					this.SendPropertyChanged("DanhMucQTLV3ID");
					this.OnDanhMucQTLV3IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhMucQTLV4ID", DbType="NVarChar(12)")]
		public string DanhMucQTLV4ID
		{
			get
			{
				return this._DanhMucQTLV4ID;
			}
			set
			{
				if ((this._DanhMucQTLV4ID != value))
				{
					this.OnDanhMucQTLV4IDChanging(value);
					this.SendPropertyChanging();
					this._DanhMucQTLV4ID = value;
					this.SendPropertyChanged("DanhMucQTLV4ID");
					this.OnDanhMucQTLV4IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhMucQTLV5ID", DbType="NVarChar(12)")]
		public string DanhMucQTLV5ID
		{
			get
			{
				return this._DanhMucQTLV5ID;
			}
			set
			{
				if ((this._DanhMucQTLV5ID != value))
				{
					this.OnDanhMucQTLV5IDChanging(value);
					this.SendPropertyChanging();
					this._DanhMucQTLV5ID = value;
					this.SendPropertyChanged("DanhMucQTLV5ID");
					this.OnDanhMucQTLV5IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVText1", DbType="NVarChar(255)")]
		public string QTLVText1
		{
			get
			{
				return this._QTLVText1;
			}
			set
			{
				if ((this._QTLVText1 != value))
				{
					this.OnQTLVText1Changing(value);
					this.SendPropertyChanging();
					this._QTLVText1 = value;
					this.SendPropertyChanged("QTLVText1");
					this.OnQTLVText1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVText2", DbType="NVarChar(255)")]
		public string QTLVText2
		{
			get
			{
				return this._QTLVText2;
			}
			set
			{
				if ((this._QTLVText2 != value))
				{
					this.OnQTLVText2Changing(value);
					this.SendPropertyChanging();
					this._QTLVText2 = value;
					this.SendPropertyChanged("QTLVText2");
					this.OnQTLVText2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVText3", DbType="NVarChar(255)")]
		public string QTLVText3
		{
			get
			{
				return this._QTLVText3;
			}
			set
			{
				if ((this._QTLVText3 != value))
				{
					this.OnQTLVText3Changing(value);
					this.SendPropertyChanging();
					this._QTLVText3 = value;
					this.SendPropertyChanged("QTLVText3");
					this.OnQTLVText3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVText4", DbType="NVarChar(255)")]
		public string QTLVText4
		{
			get
			{
				return this._QTLVText4;
			}
			set
			{
				if ((this._QTLVText4 != value))
				{
					this.OnQTLVText4Changing(value);
					this.SendPropertyChanging();
					this._QTLVText4 = value;
					this.SendPropertyChanged("QTLVText4");
					this.OnQTLVText4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVText5", DbType="NVarChar(255)")]
		public string QTLVText5
		{
			get
			{
				return this._QTLVText5;
			}
			set
			{
				if ((this._QTLVText5 != value))
				{
					this.OnQTLVText5Changing(value);
					this.SendPropertyChanging();
					this._QTLVText5 = value;
					this.SendPropertyChanged("QTLVText5");
					this.OnQTLVText5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVBoolean1", DbType="Bit")]
		public System.Nullable<bool> QTLVBoolean1
		{
			get
			{
				return this._QTLVBoolean1;
			}
			set
			{
				if ((this._QTLVBoolean1 != value))
				{
					this.OnQTLVBoolean1Changing(value);
					this.SendPropertyChanging();
					this._QTLVBoolean1 = value;
					this.SendPropertyChanged("QTLVBoolean1");
					this.OnQTLVBoolean1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVBoolean2", DbType="Bit")]
		public System.Nullable<bool> QTLVBoolean2
		{
			get
			{
				return this._QTLVBoolean2;
			}
			set
			{
				if ((this._QTLVBoolean2 != value))
				{
					this.OnQTLVBoolean2Changing(value);
					this.SendPropertyChanging();
					this._QTLVBoolean2 = value;
					this.SendPropertyChanged("QTLVBoolean2");
					this.OnQTLVBoolean2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVDate1", DbType="Date")]
		public System.Nullable<System.DateTime> QTLVDate1
		{
			get
			{
				return this._QTLVDate1;
			}
			set
			{
				if ((this._QTLVDate1 != value))
				{
					this.OnQTLVDate1Changing(value);
					this.SendPropertyChanging();
					this._QTLVDate1 = value;
					this.SendPropertyChanged("QTLVDate1");
					this.OnQTLVDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTLVDate2", DbType="Date")]
		public System.Nullable<System.DateTime> QTLVDate2
		{
			get
			{
				return this._QTLVDate2;
			}
			set
			{
				if ((this._QTLVDate2 != value))
				{
					this.OnQTLVDate2Changing(value);
					this.SendPropertyChanging();
					this._QTLVDate2 = value;
					this.SendPropertyChanged("QTLVDate2");
					this.OnQTLVDate2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel4ID", DbType="Int")]
		public System.Nullable<int> LSLevel4ID
		{
			get
			{
				return this._LSLevel4ID;
			}
			set
			{
				if ((this._LSLevel4ID != value))
				{
					this.OnLSLevel4IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel4ID = value;
					this.SendPropertyChanged("LSLevel4ID");
					this.OnLSLevel4IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel5ID", DbType="Int")]
		public System.Nullable<int> LSLevel5ID
		{
			get
			{
				return this._LSLevel5ID;
			}
			set
			{
				if ((this._LSLevel5ID != value))
				{
					this.OnLSLevel5IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel5ID = value;
					this.SendPropertyChanged("LSLevel5ID");
					this.OnLSLevel5IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel6ID", DbType="Int")]
		public System.Nullable<int> LSLevel6ID
		{
			get
			{
				return this._LSLevel6ID;
			}
			set
			{
				if ((this._LSLevel6ID != value))
				{
					this.OnLSLevel6IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel6ID = value;
					this.SendPropertyChanged("LSLevel6ID");
					this.OnLSLevel6IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel7ID", DbType="Int")]
		public System.Nullable<int> LSLevel7ID
		{
			get
			{
				return this._LSLevel7ID;
			}
			set
			{
				if ((this._LSLevel7ID != value))
				{
					this.OnLSLevel7IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel7ID = value;
					this.SendPropertyChanged("LSLevel7ID");
					this.OnLSLevel7IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel8ID", DbType="Int")]
		public System.Nullable<int> LSLevel8ID
		{
			get
			{
				return this._LSLevel8ID;
			}
			set
			{
				if ((this._LSLevel8ID != value))
				{
					this.OnLSLevel8IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel8ID = value;
					this.SendPropertyChanged("LSLevel8ID");
					this.OnLSLevel8IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSLevel9ID", DbType="Int")]
		public System.Nullable<int> LSLevel9ID
		{
			get
			{
				return this._LSLevel9ID;
			}
			set
			{
				if ((this._LSLevel9ID != value))
				{
					this.OnLSLevel9IDChanging(value);
					this.SendPropertyChanging();
					this._LSLevel9ID = value;
					this.SendPropertyChanged("LSLevel9ID");
					this.OnLSLevel9IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSHLevel1ID", DbType="Int")]
		public System.Nullable<int> LSHLevel1ID
		{
			get
			{
				return this._LSHLevel1ID;
			}
			set
			{
				if ((this._LSHLevel1ID != value))
				{
					this.OnLSHLevel1IDChanging(value);
					this.SendPropertyChanging();
					this._LSHLevel1ID = value;
					this.SendPropertyChanged("LSHLevel1ID");
					this.OnLSHLevel1IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSHLevel2ID", DbType="Int")]
		public System.Nullable<int> LSHLevel2ID
		{
			get
			{
				return this._LSHLevel2ID;
			}
			set
			{
				if ((this._LSHLevel2ID != value))
				{
					this.OnLSHLevel2IDChanging(value);
					this.SendPropertyChanging();
					this._LSHLevel2ID = value;
					this.SendPropertyChanged("LSHLevel2ID");
					this.OnLSHLevel2IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSHLevel3ID", DbType="Int")]
		public System.Nullable<int> LSHLevel3ID
		{
			get
			{
				return this._LSHLevel3ID;
			}
			set
			{
				if ((this._LSHLevel3ID != value))
				{
					this.OnLSHLevel3IDChanging(value);
					this.SendPropertyChanging();
					this._LSHLevel3ID = value;
					this.SendPropertyChanged("LSHLevel3ID");
					this.OnLSHLevel3IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSHLevel4ID", DbType="Int")]
		public System.Nullable<int> LSHLevel4ID
		{
			get
			{
				return this._LSHLevel4ID;
			}
			set
			{
				if ((this._LSHLevel4ID != value))
				{
					this.OnLSHLevel4IDChanging(value);
					this.SendPropertyChanging();
					this._LSHLevel4ID = value;
					this.SendPropertyChanged("LSHLevel4ID");
					this.OnLSHLevel4IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSHLevel5ID", DbType="Int")]
		public System.Nullable<int> LSHLevel5ID
		{
			get
			{
				return this._LSHLevel5ID;
			}
			set
			{
				if ((this._LSHLevel5ID != value))
				{
					this.OnLSHLevel5IDChanging(value);
					this.SendPropertyChanging();
					this._LSHLevel5ID = value;
					this.SendPropertyChanged("LSHLevel5ID");
					this.OnLSHLevel5IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSHLevel6ID", DbType="Int")]
		public System.Nullable<int> LSHLevel6ID
		{
			get
			{
				return this._LSHLevel6ID;
			}
			set
			{
				if ((this._LSHLevel6ID != value))
				{
					this.OnLSHLevel6IDChanging(value);
					this.SendPropertyChanging();
					this._LSHLevel6ID = value;
					this.SendPropertyChanged("LSHLevel6ID");
					this.OnLSHLevel6IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldEmpCode", DbType="NVarChar(20)")]
		public string OldEmpCode
		{
			get
			{
				return this._OldEmpCode;
			}
			set
			{
				if ((this._OldEmpCode != value))
				{
					this.OnOldEmpCodeChanging(value);
					this.SendPropertyChanging();
					this._OldEmpCode = value;
					this.SendPropertyChanged("OldEmpCode");
					this.OnOldEmpCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_ProjectID", DbType="Int")]
		public System.Nullable<int> RE_ProjectID
		{
			get
			{
				return this._RE_ProjectID;
			}
			set
			{
				if ((this._RE_ProjectID != value))
				{
					this.OnRE_ProjectIDChanging(value);
					this.SendPropertyChanging();
					this._RE_ProjectID = value;
					this.SendPropertyChanged("RE_ProjectID");
					this.OnRE_ProjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_DemandID", DbType="Int")]
		public System.Nullable<int> RE_DemandID
		{
			get
			{
				return this._RE_DemandID;
			}
			set
			{
				if ((this._RE_DemandID != value))
				{
					this.OnRE_DemandIDChanging(value);
					this.SendPropertyChanging();
					this._RE_DemandID = value;
					this.SendPropertyChanged("RE_DemandID");
					this.OnRE_DemandIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSCostCenterID", DbType="NVarChar(12)")]
		public string LSCostCenterID
		{
			get
			{
				return this._LSCostCenterID;
			}
			set
			{
				if ((this._LSCostCenterID != value))
				{
					this.OnLSCostCenterIDChanging(value);
					this.SendPropertyChanging();
					this._LSCostCenterID = value;
					this.SendPropertyChanged("LSCostCenterID");
					this.OnLSCostCenterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEESubGroupID", DbType="Int")]
		public System.Nullable<int> LSEESubGroupID
		{
			get
			{
				return this._LSEESubGroupID;
			}
			set
			{
				if ((this._LSEESubGroupID != value))
				{
					this.OnLSEESubGroupIDChanging(value);
					this.SendPropertyChanging();
					this._LSEESubGroupID = value;
					this.SendPropertyChanged("LSEESubGroupID");
					this.OnLSEESubGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongViecDuocGiao", DbType="NVarChar(255)")]
		public string CongViecDuocGiao
		{
			get
			{
				return this._CongViecDuocGiao;
			}
			set
			{
				if ((this._CongViecDuocGiao != value))
				{
					this.OnCongViecDuocGiaoChanging(value);
					this.SendPropertyChanging();
					this._CongViecDuocGiao = value;
					this.SendPropertyChanged("CongViecDuocGiao");
					this.OnCongViecDuocGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPCode", DbType="NVarChar(50)")]
		public string SAPCode
		{
			get
			{
				return this._SAPCode;
			}
			set
			{
				if ((this._SAPCode != value))
				{
					this.OnSAPCodeChanging(value);
					this.SendPropertyChanging();
					this._SAPCode = value;
					this.SendPropertyChanged("SAPCode");
					this.OnSAPCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSPhanLoaiNoiLamViecID", DbType="NVarChar(12)")]
		public string LSPhanLoaiNoiLamViecID
		{
			get
			{
				return this._LSPhanLoaiNoiLamViecID;
			}
			set
			{
				if ((this._LSPhanLoaiNoiLamViecID != value))
				{
					this.OnLSPhanLoaiNoiLamViecIDChanging(value);
					this.SendPropertyChanging();
					this._LSPhanLoaiNoiLamViecID = value;
					this.SendPropertyChanged("LSPhanLoaiNoiLamViecID");
					this.OnLSPhanLoaiNoiLamViecIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpIDNhanVienChinh", DbType="Int")]
		public System.Nullable<int> EmpIDNhanVienChinh
		{
			get
			{
				return this._EmpIDNhanVienChinh;
			}
			set
			{
				if ((this._EmpIDNhanVienChinh != value))
				{
					if (this._HR_tblEmp1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpIDNhanVienChinhChanging(value);
					this.SendPropertyChanging();
					this._EmpIDNhanVienChinh = value;
					this.SendPropertyChanged("EmpIDNhanVienChinh");
					this.OnEmpIDNhanVienChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HR_tblEmp_HR_tblEmp", Storage="_HR_tblEmps", ThisKey="EmpID", OtherKey="EmpIDNhanVienChinh")]
		public EntitySet<HR_tblEmp> HR_tblEmps
		{
			get
			{
				return this._HR_tblEmps;
			}
			set
			{
				this._HR_tblEmps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HR_tblEmp_HR_tblEmp1", Storage="_HR_tblEmps1", ThisKey="EmpID", OtherKey="EmpID_ReportTo")]
		public EntitySet<HR_tblEmp> HR_tblEmps1
		{
			get
			{
				return this._HR_tblEmps1;
			}
			set
			{
				this._HR_tblEmps1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HR_tblEmp_HR_tblEmp", Storage="_HR_tblEmp1", ThisKey="EmpIDNhanVienChinh", OtherKey="EmpID", IsForeignKey=true)]
		public HR_tblEmp HR_tblEmp1
		{
			get
			{
				return this._HR_tblEmp1.Entity;
			}
			set
			{
				HR_tblEmp previousValue = this._HR_tblEmp1.Entity;
				if (((previousValue != value) 
							|| (this._HR_tblEmp1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HR_tblEmp1.Entity = null;
						previousValue.HR_tblEmps.Remove(this);
					}
					this._HR_tblEmp1.Entity = value;
					if ((value != null))
					{
						value.HR_tblEmps.Add(this);
						this._EmpIDNhanVienChinh = value.EmpID;
					}
					else
					{
						this._EmpIDNhanVienChinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("HR_tblEmp1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HR_tblEmp_HR_tblEmp1", Storage="_HR_tblEmp2", ThisKey="EmpID_ReportTo", OtherKey="EmpID", IsForeignKey=true)]
		public HR_tblEmp HR_tblEmp2
		{
			get
			{
				return this._HR_tblEmp2.Entity;
			}
			set
			{
				HR_tblEmp previousValue = this._HR_tblEmp2.Entity;
				if (((previousValue != value) 
							|| (this._HR_tblEmp2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HR_tblEmp2.Entity = null;
						previousValue.HR_tblEmps1.Remove(this);
					}
					this._HR_tblEmp2.Entity = value;
					if ((value != null))
					{
						value.HR_tblEmps1.Add(this);
						this._EmpID_ReportTo = value.EmpID;
					}
					else
					{
						this._EmpID_ReportTo = default(Nullable<int>);
					}
					this.SendPropertyChanged("HR_tblEmp2");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HR_tblEmps(HR_tblEmp entity)
		{
			this.SendPropertyChanging();
			entity.HR_tblEmp1 = this;
		}
		
		private void detach_HR_tblEmps(HR_tblEmp entity)
		{
			this.SendPropertyChanging();
			entity.HR_tblEmp1 = null;
		}
		
		private void attach_HR_tblEmps1(HR_tblEmp entity)
		{
			this.SendPropertyChanging();
			entity.HR_tblEmp2 = this;
		}
		
		private void detach_HR_tblEmps1(HR_tblEmp entity)
		{
			this.SendPropertyChanging();
			entity.HR_tblEmp2 = null;
		}
	}
}
#pragma warning restore 1591
