<?xml version="1.0" encoding="utf-8"?><Database Name="up6" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-3CG3R38\SQLEXPRESS;Initial Catalog=up6;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="up6ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.canboql" Member="canboqls">
    <Type Name="canboql">
      <Column Name="macbql" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="idmadoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="madp" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="canboql_nguoisudung" Member="nguoisudungs" ThisKey="macbql" OtherKey="macbql" Type="nguoisudung" />
      <Association Name="canboql_SoLieuTuNganHang" Member="SoLieuTuNganHangs" ThisKey="macbql" OtherKey="macbql" Type="SoLieuTuNganHang" />
      <Association Name="DoiThue_canboql" Member="DoiThue" ThisKey="idmadoi" OtherKey="idmadoi" Type="DoiThue" IsForeignKey="true" />
      <Association Name="maduongpho_canboql" Member="maduongpho" ThisKey="madp" OtherKey="madp" Type="maduongpho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.truythu" Member="truythus">
    <Type Name="truythu">
      <Column Name="IDtruythu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="doanhso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TiLeTinhThue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KyThue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Association Name="DanhBa_truythu" Member="DanhBa" ThisKey="masothue" OtherKey="masothue" Type="DanhBa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietKhaiThue" Member="ChiTietKhaiThues">
    <Type Name="ChiTietKhaiThue">
      <Column Name="idChiTiet" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DoanhThu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoTienGTGT1Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTienTNCN1Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongSoTienNop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="manganh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KhaiThue_ChiTietKhaiThue" Member="KhaiThue" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="KhaiThue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.coquanthue" Member="coquanthues">
    <Type Name="coquanthue">
      <Column Name="macoquan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tengoi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="machicuc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="coquanthue_DoiThue" Member="DoiThues" ThisKey="macoquan" OtherKey="macoquan" Type="DoiThue" />
    </Type>
  </Table>
  <Table Name="dbo.DanhBa" Member="DanhBas">
    <Type Name="DanhBa">
      <Column Name="ngaycapmst" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tencuahang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="thutu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="cmnd" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ngaycapcmnd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="noicapcmnd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachicutru" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachiKD" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="chanle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sonha" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="madp" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="vonkd" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ngaybatdaukd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngaytinhthue" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="sogp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ngaycapgp" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="sodtban" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="sodt" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Association Name="DanhBa_truythu" Member="truythus" ThisKey="masothue" OtherKey="masothue" Type="truythu" />
      <Association Name="DanhBa_KhaiThue" Member="KhaiThues" ThisKey="masothue" OtherKey="masothue" Type="KhaiThue" />
      <Association Name="DanhBa_sodu" Member="sodus" ThisKey="masothue" OtherKey="masothue" Type="sodu" />
      <Association Name="DanhBa_SoLieuTuNganHang" Member="SoLieuTuNganHangs" ThisKey="masothue" OtherKey="masothue" Type="SoLieuTuNganHang" />
      <Association Name="DanhBa_sono" Member="sonos" ThisKey="masothue" OtherKey="masothue" Type="sono" />
      <Association Name="maduongpho_DanhBa" Member="maduongpho" ThisKey="madp" OtherKey="madp" Type="maduongpho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoiThue" Member="DoiThues">
    <Type Name="DoiThue">
      <Column Name="idmadoi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="madoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tendoi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenvt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="macoquan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DoiThue_canboql" Member="canboqls" ThisKey="idmadoi" OtherKey="idmadoi" Type="canboql" />
      <Association Name="coquanthue_DoiThue" Member="coquanthue" ThisKey="macoquan" OtherKey="macoquan" Type="coquanthue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhaiThue" Member="KhaiThues">
    <Type Name="KhaiThue">
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="TongDoanhThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="manganh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DienTichKD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoLuongLD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaykhaithue" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThaiHoatDong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Lan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TuGio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DenGio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KhaiThue_ChiTietKhaiThue" Member="ChiTietKhaiThues" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="ChiTietKhaiThue" />
      <Association Name="KhaiThue_SoBoThue" Member="SoBoThues" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="SoBoThue" />
      <Association Name="KhaiThue_ThongBaoNopThue" Member="ThongBaoNopThues" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="ThongBaoNopThue" />
      <Association Name="KhaiThue_thongtinngungnghi" Member="thongtinngungnghis" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="thongtinngungnghi" />
      <Association Name="KhaiThue_thuemonbai" Member="thuemonbais" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="thuemonbai" />
      <Association Name="DanhBa_KhaiThue" Member="DanhBa" ThisKey="masothue" OtherKey="masothue" Type="DanhBa" IsForeignKey="true" />
      <Association Name="manganh_KhaiThue" Member="manganh1" ThisKey="manganh" OtherKey="manganh1" Type="manganh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.maduongpho" Member="maduongphos">
    <Type Name="maduongpho">
      <Column Name="madp" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenduong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenvt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="maduongpho_canboql" Member="canboqls" ThisKey="madp" OtherKey="madp" Type="canboql" />
      <Association Name="maduongpho_DanhBa" Member="DanhBas" ThisKey="madp" OtherKey="madp" Type="DanhBa" />
    </Type>
  </Table>
  <Table Name="dbo.manganh" Member="manganhs">
    <Type Name="manganh">
      <Column Name="manganh" Member="manganh1" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tennganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tenvt" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TyLeTinhThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TyLeTinhThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="manganh_KhaiThue" Member="KhaiThues" ThisKey="manganh1" OtherKey="manganh" Type="KhaiThue" />
    </Type>
  </Table>
  <Table Name="dbo.mucluc_MonBai" Member="mucluc_MonBais">
    <Type Name="mucluc_MonBai">
      <Column Name="Bac" Type="System.String" DbType="NVarChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MucThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="mucluc_MonBai_thuemonbai" Member="thuemonbais" ThisKey="Bac" OtherKey="Bac" Type="thuemonbai" />
    </Type>
  </Table>
  <Table Name="dbo.mucluc_thue" Member="mucluc_thues">
    <Type Name="mucluc_thue">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="muc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tieumuc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tengoi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tungay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="denngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.nguoisudung" Member="nguoisudungs">
    <Type Name="nguoisudung">
      <Column Name="ma" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="loainguoisudung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="macbql" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="canboql_nguoisudung" Member="canboql" ThisKey="macbql" OtherKey="macbql" Type="canboql" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SoBoThue" Member="SoBoThues">
    <Type Name="SoBoThue">
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idSoBoThue" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangNopThue" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLapBo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueGTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLeTinhThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TyLeTinhThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoTienGTGT1Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTienTNCN1Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhaiThue_SoBoThue" Member="KhaiThue" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="KhaiThue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sodu" Member="sodus">
    <Type Name="sodu">
      <Column Name="idSoDu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KyThue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tieumuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Association Name="DanhBa_sodu" Member="DanhBa" ThisKey="masothue" OtherKey="masothue" Type="DanhBa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SoLieuTuNganHang" Member="SoLieuTuNganHangs">
    <Type Name="SoLieuTuNganHang">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="macbql" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SoTienNop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayNop" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="KyThue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tieumuc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="muc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="canboql_SoLieuTuNganHang" Member="canboql" ThisKey="macbql" OtherKey="macbql" Type="canboql" IsForeignKey="true" />
      <Association Name="DanhBa_SoLieuTuNganHang" Member="DanhBa" ThisKey="masothue" OtherKey="masothue" Type="DanhBa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sono" Member="sonos">
    <Type Name="sono">
      <Column Name="idSoNo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KyThue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tieumuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Association Name="DanhBa_sono" Member="DanhBa" ThisKey="masothue" OtherKey="masothue" Type="DanhBa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.testTriggerTinhThue" Member="testTriggerTinhThues">
    <Type Name="testTriggerTinhThue">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ThongBaoNopThue" Member="ThongBaoNopThues">
    <Type Name="ThongBaoNopThue">
      <Column Name="KyThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThueGTGN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThueMonBai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idThongBao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="KhaiThue_ThongBaoNopThue" Member="KhaiThue" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="KhaiThue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.thongtinngungnghi" Member="thongtinngungnghis">
    <Type Name="thongtinngungnghi">
      <Column Name="mattngungnghi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tungay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="denngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lydo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ngaynopdon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhaiThue_thongtinngungnghi" Member="KhaiThue" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="KhaiThue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.thue" Member="thues">
    <Type Name="thue">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KyThue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TiLeTinhThue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="idMucluc_thue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idChiTiet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTienNop" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.thuemonbai" Member="thuemonbais">
    <Type Name="thuemonbai">
      <Column Name="idMonBai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Bac" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhaiThue_thuemonbai" Member="KhaiThue" ThisKey="idKhaiThue" OtherKey="idKhaiThue" Type="KhaiThue" IsForeignKey="true" />
      <Association Name="mucluc_MonBai_thuemonbai" Member="mucluc_MonBai" ThisKey="Bac" OtherKey="Bac" Type="mucluc_MonBai" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.ChamBoThue" Method="ChamBoThue">
    <Parameter Name="idSoBoThue" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="ReturnMess" Parameter="returnMess" Type="System.String" DbType="NVarChar(500)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Update_ChiTietKhaiThue" Method="Update_ChiTietKhaiThue">
    <Parameter Name="idchitiet" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="DoanhThu" Parameter="doanhThu" Type="System.Int32" DbType="Int" />
    <Parameter Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="manganh" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="ReturnCode" Parameter="returnCode" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Parameter Name="ReturnMess" Parameter="returnMess" Type="System.String" DbType="NVarChar(500)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ChamBoThue_LoadData" Method="ChamBoThue_LoadData">
    <Parameter Name="MST" Parameter="mST" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="NgheKinhDoanh" Parameter="ngheKinhDoanh" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="DiaChi" Parameter="diaChi" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(250)" />
    <ElementType Name="ChamBoThue_LoadDataResult">
      <Column Name="idSoBoThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachiKD" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckTrung_ChitietKhaiThue" Method="CheckTrung_ChitietKhaiThue">
    <Parameter Name="strXML" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="strXML2" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ReturnMess" Parameter="returnMess" Type="System.String" DbType="NVarChar(50)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DanhSachHoCaThe" Method="DanhSachHoCaThe">
    <Parameter Name="MST" Parameter="mST" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="TenCuaHang" Parameter="tenCuaHang" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NgayCap" Parameter="ngayCap" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="SoGP" Parameter="soGP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DiaChi" Parameter="diaChi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NgayTinhThue" Parameter="ngayTinhThue" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="SDT" Parameter="sDT" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="Activity" Parameter="activity" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="DanhSachHoCaTheResult">
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="cmnd" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngaycapmst" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngaytinhthue" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="sodt" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="tencuahang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachiKD" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ngaybatdaukd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="sogp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DanhSachKhaiThue_Import" Method="DanhSachKhaiThue_Import">
    <Parameter Name="masothue" Type="System.String" DbType="NVarChar(140)" />
    <Parameter Name="nam" Type="System.String" DbType="NVarChar(4)" />
    <Parameter Name="ngaykhaithue" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="manganh" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="TuGio" Parameter="tuGio" Type="System.Int32" DbType="Int" />
    <Parameter Name="DenGio" Parameter="denGio" Type="System.Int32" DbType="Int" />
    <Parameter Name="trangthai" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="soluongLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="doanhthu" Type="System.Double" DbType="Float" />
    <Parameter Name="dientichKD" Type="System.Double" DbType="Float" />
    <Parameter Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DanhSachThongTinHoCaThe" Method="DanhSachThongTinHoCaThe">
    <Parameter Name="idSoBoThue" Type="System.Int32" DbType="Int" />
    <ElementType Name="DanhSachThongTinHoCaTheResult">
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tieumuc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tengoi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoTienDaNop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTienConNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTienDu" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDanhSachTongTienPhaiThu" Method="GetDanhSachTongTienPhaiThu">
    <Parameter Name="thang" Type="System.String" DbType="NVarChar(7)" />
    <ElementType Name="GetDanhSachTongTienPhaiThuResult">
      <Column Name="SoTienGTGT1Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTienTNCN1Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongSoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongDoanhThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDSChuaLapBo" Method="GetDSChuaLapBo">
    <Parameter Name="idKhaiThue" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="thang" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetDSChuaLapBoResult">
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idSoBoThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangNopThue" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayLapBo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueGTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLeTinhThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TyLeTinhThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoTienGTGT1Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTienTNCN1Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDsConNo" Method="getDsConNo">
    <Parameter Name="masothue" Type="System.String" DbType="NVarChar(15)" />
    <ElementType Name="getDsConNoResult">
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="KyThue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tieumuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDSHoDuocLenSoBo" Method="getDSHoDuocLenSoBo">
    <ElementType Name="getDSHoDuocLenSoBoResult">
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="sodt" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tennganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoLuongLD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienTichKD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diachiKD" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TrangThaiHoatDong" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TongDoanhThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueGTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLeTinhThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TyLeTinhThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TuGio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DenGio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDSNgungNghi" Method="GetDSNgungNghi">
    <Parameter Name="MST" Parameter="mST" Type="System.String" DbType="NVarChar(15)" />
    <ElementType Name="GetDSNgungNghiResult">
      <Column Name="tuthang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="denthang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lydo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ngaynopdon" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDSSoBoThue" Method="getDSSoBoThue">
    <Parameter Name="MST" Parameter="mST" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="NgheKinhDoanh" Parameter="ngheKinhDoanh" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Thang" Parameter="thang" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="DiaChi" Parameter="diaChi" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="ThangLapBo" Parameter="thangLapBo" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="Nam" Parameter="nam" Type="System.String" DbType="VarChar(4)" />
    <ElementType Name="getDSSoBoThueResult">
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayLapBo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="diachiKD" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangNopThue" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="DoanhThuTinhThueGTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLeTinhThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThueGTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLeTinhThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idSoBoThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MucThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDSThue" Method="getDSThue">
    <Parameter Name="masothue" Type="System.String" DbType="VarChar(14)" />
    <Parameter Name="sogiayphep" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="manganh" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="nam" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="TrangThai" Parameter="trangThai" Type="System.String" DbType="NVarChar(1)" />
    <ElementType Name="getDSThueResult">
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="TongDoanhThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="lankhaithue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bac" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="diachiKD" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TrangThaiHoatDong" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sogp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tennganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="mattngungnghi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tungay" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="denngay" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ngaynopdon" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSoThueMonBai" Method="GetSoThueMonBai">
    <Parameter Name="thang" Type="System.String" DbType="NVarChar(7)" />
    <ElementType Name="GetSoThueMonBaiResult">
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="vonkd" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Bac" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="MucThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSoThueNgungNghi" Method="GetSoThueNgungNghi">
    <Parameter Name="thang" Type="System.String" DbType="NVarChar(7)" />
    <ElementType Name="GetSoThueNgungNghiResult">
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongDoanhThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getThongBaoNopThue" Method="getThongBaoNopThue">
    <Parameter Name="thang" Type="System.String" DbType="NVarChar(7)" />
    <ElementType Name="getThongBaoNopThueResult">
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="diachiKD" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="KyThue" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="KyThue2" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThueGTGN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThueMonBai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Insert_ChitietKhaiThue" Method="Insert_ChitietKhaiThue">
    <Parameter Name="strXML" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="Insert_ChitietKhaiThueResult">
      <Column Name="idKhaiThue" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="idchitiet" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="DoanhThu" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="NgheKinhDoanh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="manganh" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Insert_ChitietKhaiThue_NotXML" Method="Insert_ChitietKhaiThue_NotXML">
    <Parameter Name="idKhaiThue" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="DoanhThu" Parameter="doanhThu" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="manganh" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insert_HoCaThe" Method="Insert_HoCaThe">
    <Parameter Name="masothue" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="ngaycapmst" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tencuahang" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ngaysinh" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ngaycapcmnd" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="madp" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="nam" Type="System.String" DbType="NVarChar(4)" />
    <Parameter Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="vonkinhdoanh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaybatdaukd" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ngaytinhthue" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="sogiayphep" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sodienthoai" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insert_KhaiThue" Method="Insert_KhaiThue">
    <Parameter Name="idKhaiThue" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="masothue" Type="System.String" DbType="VarChar(14)" />
    <Parameter Name="nam" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="DienTichKD" Parameter="dienTichKD" Type="System.Double" DbType="Float" />
    <Parameter Name="SoLuongLD" Parameter="soLuongLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="TuGio" Parameter="tuGio" Type="System.Int32" DbType="Int" />
    <Parameter Name="DenGio" Parameter="denGio" Type="System.Int32" DbType="Int" />
    <Parameter Name="TrangThaiHoatDong" Parameter="trangThaiHoatDong" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ngaykhaithue" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ReturnCode" Parameter="returnCode" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Parameter Name="ReturnMess" Parameter="returnMess" Type="System.String" DbType="NVarChar(500)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insert_SoBoThue" Method="Insert_SoBoThue">
    <Parameter Name="idKhaiThue" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="NgayLapBo" Parameter="ngayLapBo" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Thang" Parameter="thang" Type="System.Int32" DbType="Int" />
    <Parameter Name="DoanhThuTinhThueGTGT" Parameter="doanhThuTinhThueGTGT" Type="System.Int32" DbType="Int" />
    <Parameter Name="DoanhThuTinhThueTNCN" Parameter="doanhThuTinhThueTNCN" Type="System.Int32" DbType="Int" />
    <Parameter Name="TyLeTinhThueGTGT" Parameter="tyLeTinhThueGTGT" Type="System.Double" DbType="Float" />
    <Parameter Name="TyLeTinhThueTNCN" Parameter="tyLeTinhThueTNCN" Type="System.Double" DbType="Float" />
    <Parameter Name="RessMess" Parameter="ressMess" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insert_SoLieuNopThue" Method="Insert_SoLieuNopThue">
    <Parameter Name="masothue" Type="System.String" DbType="NVarChar(14)" />
    <Parameter Name="macbql" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="sotiennop" Type="System.Double" DbType="Float" />
    <Parameter Name="ngaynop" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="KyThue" Parameter="kyThue" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="tieumuc" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="muc" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Load_ChiTietKhaiThue" Method="Load_ChiTietKhaiThue">
    <Parameter Name="idKhaiThue" Type="System.String" DbType="NVarChar(14)" />
    <ElementType Name="Load_ChiTietKhaiThueResult">
      <Column Name="idChiTiet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Seq" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="manganh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tennganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DoanhThu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TyLeTinhThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TyLeTinhThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgheKinhDoanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LoadChiTietKhaiThueXML" Method="LoadChiTietKhaiThueXML">
    <Parameter Name="strXML" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ReturnCode" Parameter="returnCode" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Parameter Name="ReturnMess" Parameter="returnMess" Type="System.String" DbType="NVarChar(500)" Direction="InOut" />
    <Parameter Name="Activity" Parameter="activity" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="LoadChiTietKhaiThueXMLResult">
      <Column Name="idKhaiThue" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="idchitiet" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="DoanhThu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgheKinhDoanh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="manganh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tennganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TyLeTinhThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TyLeTinhThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Seq" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_frmKTDangNhap" Method="sp_frmKTDangNhap">
    <Parameter Name="TenDangNhap" Parameter="tenDangNhap" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MatKhau" Parameter="matKhau" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ReturnMess" Parameter="returnMess" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spfrm_SoBoThue" Method="spfrm_SoBoThue">
    <Parameter Name="MST" Parameter="mST" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="TenCuaHang" Parameter="tenCuaHang" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="ngaycapCMND" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="sogp" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ngaytinhthue" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="manganh" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="idKhaiThue" Type="System.Int32" DbType="Int" />
    <Parameter Name="Activity" Parameter="activity" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ReturnMess" Parameter="returnMess" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spfrm_SoBoThueResult">
      <Column Name="idKhaiThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masothue" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="nam" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="sodt" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tennganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoLuongLD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienTichKD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diachiKD" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TrangThaiHoatDong" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TongDoanhThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueGTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoanhThuTinhThueTNCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLeTinhThueGTGT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TyLeTinhThueTNCN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TuGio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DenGio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nghekinhdoanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MucThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>